#!/usr/bin/env python3
"""Build the Anki-importable TSV decks and the markdown study guide.

Run:  python3 src/build.py
Outputs:
  decks/<nn>-<key>.tsv        one file per syllabus section, with Anki header lines
  decks/rya-day-skipper-all.tsv   everything in one file
  STUDY-GUIDE.md              the same content as a readable revision document

The card source is `cards/` — markdown, parsed by content/mdc.py, the same
parser the web build reads through, so the two outputs cannot drift apart.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.dirname(ROOT))

import mdc                              # noqa: E402

CARDS = os.path.join(ROOT, "cards")
DECKS = os.path.join(ROOT, "build", "decks")
MEDIA = os.path.join(ROOT, "media")


def main():
    os.makedirs(DECKS, exist_ok=True)
    for f in os.listdir(DECKS):
        if f.endswith(".tsv"):
            os.remove(os.path.join(DECKS, f))

    deck = mdc.parse_course(CARDS)
    top = deck.name

    errors, all_rows, guide, used_media = [], [], [], set()
    total = 0

    for s in deck.sections:
        anki_deck = f"{top}::{s.title}"
        rows = []
        guide.append(f"\n## {s.title}\n")
        for c in s.cards:
            # A labelled drawing is inline SVG in the web app and has no file
            # to ship with a deck. Anki and the guide carry the PNGs only.
            img = c.img
            if img and not os.path.isfile(os.path.join(MEDIA, img)):
                errors.append(f"{c.where}: missing media file {img}")
            body = c.a
            if img:
                used_media.add(img)
                body = f'{c.a}<br><br><img src="{img}">'
            tags = f"RYA DaySkipper {s.key}"
            rows.append(f"{c.q}\t{body}\t{tags}")
            all_rows.append(f"{c.q}\t{body}\t{tags}\t{anki_deck}")
            guide.append(f"**{c.q}**\n")
            plain = c.a.replace("<b>", "**").replace("</b>", "**")
            plain = plain.replace("<u>", "_").replace("</u>", "_")
            plain = re.sub(r"<br\s*/?>", "  \n", plain)
            guide.append(f"{plain}\n")
            if img:
                guide.append(f"![{s.key} diagram](media/{img})\n")
            total += 1

        path = os.path.join(DECKS, f"{s.order:02d}-{s.key}.tsv")
        with open(path, "w", encoding="utf-8") as f:
            f.write("#separator:tab\n#html:true\n#notetype:Basic\n")
            f.write(f"#deck:{anki_deck}\n#tags column:3\n")
            f.write("\n".join(rows) + "\n")

    with open(os.path.join(DECKS, "rya-day-skipper-all.tsv"), "w", encoding="utf-8") as f:
        f.write("#separator:tab\n#html:true\n#notetype:Basic\n")
        f.write("#tags column:3\n#deck column:4\n")
        f.write("\n".join(all_rows) + "\n")

    header = f"""# RYA Day Skipper — study guide

Companion to the Anki deck in `decks/`. {total} question-and-answer items across
{len(deck.sections)} sections, following the RYA Day Skipper shorebased and practical
syllabus. Diagrams in `media/` are original artwork generated by `src/diagrams.py`.

This is revision material, not a substitute for the RYA course, the current
almanac, or an up-to-date chart. Verify any figure that you are going to rely on
at sea against the official publication.
"""
    with open(os.path.join(ROOT, "build", "STUDY-GUIDE.md"), "w", encoding="utf-8") as f:
        f.write(header + "\n".join(guide) + "\n")

    unused = sorted(set(os.listdir(MEDIA)) - used_media)
    print(f"sections : {len(deck.sections)}")
    print(f"cards    : {total}")
    print(f"images   : {len(used_media)} of {len(os.listdir(MEDIA))} referenced")
    if unused:
        print(f"unused   : {', '.join(unused)}")
    if errors:
        print(f"\n{len(errors)} PROBLEMS:")
        for e in errors[:40]:
            print("  " + e)
        sys.exit(1)
    print("\nvalidation clean")


if __name__ == "__main__":
    main()
