# -*- coding: utf-8 -*-
"""RYA Day Skipper cards, part C: pilotage, emergencies, engines, boat handling, passage planning."""

SECTIONS_C = [
("pilotage", "17 Pilotage", [
 ("What is the difference between navigation and pilotage?",
  "<b>Navigation</b> is getting from A to B in open water using the chart, the tide and the compass, with time to plot. <b>Pilotage</b> is close-quarters work near the shore where there is no time to plot: you work from a prepared plan, marks, transits, depths and eyeball.", "ds-fix-pilotage.png"),
 ("What goes into a pilotage plan?",
  "A simple sketch you can read one-handed in the dark:<br>the legs with courses and distances,<br>the buoys and lights in the order you will see them with their characteristics,<br>transits and leading lines,<br>clearing bearings for each hazard,<br>a depth contour to stay outside,<br>the tidal height needed and when,<br>waypoints,<br>and an <b>abort plan</b>.", "ds-fix-pilotage.png"),
 ("Why is a transit better than a compass bearing?",
  "It has <b>no error at all</b> — no variation, no deviation, no reading error — and it shows you instantly whether you are drifting off the line. Two charted objects in line is the most reliable pilotage tool there is.", "ds-fix-pilotage.png"),
 ("What is a leading line?",
  "A charted line, usually defined by two marks or two lights in transit, that leads safely into a harbour or through a channel. The chart gives its bearing; the marks give you the accuracy.", "ds-fix-pilotage.png"),
 ("What is a clearing bearing and how do you use it?",
  "A bearing of a charted object which, if you keep the actual bearing greater than (or less than) it, keeps you clear of a danger. Written as 'keep the bearing of the church spire greater than 070&deg;', or NLT / NMT on the chart — a single number the helm can hold without looking at the chart.", "ds-fix-pilotage.png"),
 ("How do you use the echo sounder as a safety line?",
  "Choose a depth contour that clears the dangers, work out what the sounder should read at that contour for the height of tide at the time, and treat that number as a wall: if the depth falls to it, turn away. It works in fog and at night."),
 ("What is a head bearing, and what is it good for?",
  "The bearing of a mark you are heading towards. Watch it: if it stays constant you are making good the track towards the mark; if it changes, the tide is setting you off and you must alter."),
 ("What is the practical rule about speed in pilotage?",
  "Go slowly enough that you can keep ahead of the boat. If you cannot identify the next mark before you reach the last one, slow down, stop, or turn back onto a reciprocal course until you have sorted out where you are."),
 ("What preparation should be done on deck before entering a harbour?",
  "Fenders and warps rigged both sides,<br>boat hook to hand,<br>anchor ready to let go,<br>sails stowed or ready to drop,<br>engine warm and tested in ahead and astern,<br>crew briefed with jobs allocated,<br>and the pilotage plan and VHF channel to hand in the cockpit."),
 ("Why brief the crew before the entrance rather than during it?",
  "Because once you are in it you will be busy with the helm and the marks, and a shouted instruction in a confined channel is how boats get damaged. Allocate helm,<br>lookout,<br>fenders,<br>lines and log-keeper in advance."),
 ("What information do you look up before entering an unfamiliar harbour?",
  "Approach and entrance in the pilot book and almanac,<br>harbour plan,<br>tidal height and stream at your arrival time,<br>any bar, sill or lock and its operating hours,<br>port signals and traffic lights,<br>VHF working channel and whether you must call in,<br>visitor berths,<br>prohibited areas,<br>and the abort options if you cannot get in."),
 ("What do port entry traffic signals typically mean?",
  "Three <b>flashing</b> red lights in a vertical line = serious emergency, all vessels stop or divert as instructed (IPTS 1).<br>Three <b>fixed</b> reds = vessels shall not proceed (IPTS 2).<br>Red, white, red = do not proceed except outside the main channel (IPTS 3).<br>Three greens = proceed, one-way traffic;<br>green, white, green = proceed, two-way traffic. Local variations exist, so read the almanac entry for the specific port before you rely on it."),
 ("What is 'IPTS'?",
  "The International Port Traffic Signals, a standardised set of light signals controlling movement in and out of harbours, described in the almanac. A single yellow light alongside the main signal often exempts small craft — but only where the port says so."),
 ("How do you handle pilotage at night?",
  "Prepare everything in daylight,<br>preserve night vision with red light and no white deck lights,<br>identify each light by counting its period rather than guessing,<br>use the order of lights in your plan,<br>post a dedicated lookout free of other tasks,<br>and go slower than you would by day. Background shore lights make buoys very hard to pick out."),
 ("Why are lit buoys so hard to spot on the approach to a lit town?",
  "Because a 3-mile flashing buoy competes with streetlights, illuminated signs and moving car headlights ashore. Use transits,<br>leading lights,<br>depth and your prepared bearings, not just buoy-hopping."),
 ("What is an abort plan and when do you decide to use it?",
  "The pre-agreed route back out to safe water, with the course to steer and the depth you expect. Decide the <b>trigger</b> in advance —<br>cannot identify the leading marks,<br>too much wind across the entrance,<br>not enough depth,<br>traffic in the channel<br>— and act on it early rather than pressing on."),
 ("How does the tidal stream inside a harbour entrance differ from outside?",
  "It can reverse, accelerate through the gap, and set strongly across the entrance or along a pontoon face. Expect an eddy behind a breakwater running the opposite way to the main stream, and plan the last hundred metres for it."),
]),

("fog", "18 Restricted visibility", [
 ("What actions do you take when fog closes in?",
  "Fix your position immediately while you still can.<br>Slow to a safe speed, engine on and ready.<br>Sound the fog signal.<br>Show navigation lights.<br>Lifejackets on and crew on deck as extra lookouts, listening as well as looking.<br>Hoist the radar reflector.<br>Get out of shipping lanes and busy channels.<br>Plot continuously and consider anchoring in shallow water clear of the fairway."),
 ("Which rule governs your conduct in fog, and what is different about it?",
  "<b>Rule 19</b>. It applies when vessels are not in sight of one another in or near restricted visibility, and there is <b>no stand-on vessel</b> — every vessel has an obligation to avoid collision.", "ds-colregs-sail.png"),
 ("Why is it safer to be in shallow water in fog?",
  "Because commercial traffic cannot follow you there. Getting outside the buoyed channel into water too shallow for shipping, or anchoring there, removes the biggest single threat."),
 ("Why anchor rather than keep moving in thick fog?",
  "An anchored boat is not closing anything,<br>is easier to fix,<br>sounds a distinctive signal,<br>and lets you listen properly. Anchor clear of the channel,<br>sound the bell signal,<br>and keep a lookout."),
 ("What should you listen for in fog, and how reliable is it?",
  "Fog signals,<br>engine noise,<br>breaking water on a shore,<br>and bell buoys. Sound in fog is deceptive: it can be deflected, reflected and blanketed, so a signal can seem to come from the wrong direction or be inaudible in a 'shadow'. Never bet your position on hearing alone."),
 ("How useful is a small-craft radar reflector in practice?",
  "Better than nothing, but a yacht is a poor radar target, especially heeled or in a rough sea where sea clutter hides her. Assume you have <b>not</b> been seen and keep out of the way."),
 ("What is AIS and how does it help in poor visibility?",
  "The Automatic Identification System broadcasts a vessel's identity, position, course and speed over VHF. A receiver shows you shipping with its CPA and TCPA. An AIS transponder makes you visible to them too. It does not show vessels without AIS, and small craft often carry none."),
 ("What is CPA and TCPA?",
  "<b>Closest Point of Approach</b> — how near the other vessel will pass if nothing changes.<br><b>Time to CPA</b> — how long until that happens. They are the two numbers that tell you whether you have a problem and how long you have to solve it."),
 ("What are the fog signals you are most likely to hear from a big ship, and what do they mean?",
  "One prolonged blast at intervals of <b>not more than</b> 2 minutes — a power-driven vessel <b>making way</b>.<br>Two prolonged blasts about 2 seconds apart — a power-driven vessel underway but <b>stopped</b>.<br>One prolonged and two short — a sailing vessel, or a vessel fishing, towing or pushing, not under command, restricted in her ability to manoeuvre, or constrained by draught. All at intervals of not more than 2 minutes.", "ds-sound-signals.png"),
 ("Should you use the engine in fog if you are under sail?",
  "Usually yes: it gives you manoeuvrability and the ability to stop, which Rule 19 expects. But turn it off periodically, or have a crew member well forward, so you can listen. Remember that once under power you must show the correct lights, hoist the black <b>cone, point down</b>, forward by day, and that your fog signal changes from one prolonged and two short to <b>one prolonged</b>."),
 ("What is the greatest danger to a yacht in fog in the Channel?",
  "Being run down by shipping that cannot see you and may not detect you on radar, especially in or near a traffic separation scheme or the approaches to a major port. Cross the lanes at right angles, quickly, and preferably not in fog at all."),
]),

("emergencies", "19 Emergencies", [
 ("What are the immediate actions for a man overboard?",
  "Shout 'man overboard' to get everyone on deck;<br><b>throw</b> buoyancy — danbuoy and lifebuoy — immediately;<br>detail one person to <b>point</b> at the casualty and do nothing else;<br>press the MOB button on the plotter or GNSS;<br>start the engine, checking for lines over the side;<br>and manoeuvre back to the casualty.", "ds-mob.png"),
 ("Describe the reach-tack-reach MOB recovery under sail.",
  "Get onto a <b>beam reach</b> — bearing away if you were beating, luffing up if you were running — and sail on for four to six boat lengths.<br><b>Tack</b>, never gybe.<br>Come onto the reciprocal beam reach, bear away enough to get to leeward of the casualty, then turn up and approach on a <b>close reach</b>, controlling speed by easing the sails.<br>Stop with the casualty alongside on the <b>leeward</b> side at or just forward of the shrouds, engine out of gear — never ahead of the bow, where you lose sight of them.", "ds-mob.png"),
 ("Describe the crash-stop (heave-to) MOB recovery.",
  "Tack immediately without touching the headsail sheet, so the headsail is left backed. The boat stops quickly and stays near the casualty. Then drop or furl the headsail and motor or sail the last few lengths. Its virtue is that you never get far from the casualty. Note that the American <b>Quick Stop</b> is a different manoeuvre: you keep turning through a gybe and circle back.", "ds-mob.png"),
 ("Why do you approach a man overboard from downwind, and stop with them to leeward?",
  "Approaching from downwind on a close reach lets you spill the sails to control speed and stop. Recover on the <b>leeward</b> side because a yacht blows downwind far faster than a person in the water, so a casualty left to windward is one you drift away from; the hull also gives them a lee, and the heeled leeward rail is the lowest freeboard. Stop the boat and take the engine out of gear before they are anywhere near the hull.", "ds-mob.png"),
 ("Why should the engine be out of gear before anyone comes alongside the hull?",
  "Because the propeller will kill or maim someone in the water. Neutral, and preferably stopped, before the casualty is anywhere near the stern or the boarding ladder.", "ds-mob.png"),
 ("Why lift a MOB casualty horizontally if you can?",
  "Because prolonged immersion causes the blood to pool in the legs. Lifting vertically can drop the blood pressure and cause post-immersion collapse and cardiac arrest. Keep them horizontal during and after recovery, and handle them gently."),
 ("How can you get a casualty back on board a yacht?",
  "A boarding ladder if they can climb;<br>a lifting strop or MOB recovery sling on a spare halyard led to a winch;<br>the mainsail or a sail used as a scoop under them;<br>a bight of rope as a step;<br>or the dinghy. Practise it — a wet, cold adult in oilskins is an extraordinarily heavy lift."),
 ("When would you send a MAYDAY for a man overboard?",
  "As soon as you lose sight of the casualty, or if you are short-handed, or if the first recovery attempt fails, or if there is any injury. It is far better to cancel a MAYDAY than to send it too late.", "ds-vhf-distress.png"),
 ("What is a MAYDAY and how do you send one?",
  "The distress signal for grave and imminent danger. Press and hold the <b>DSC distress</b> button for 5 seconds first, then on Ch 16:<br>MAYDAY &times;3,<br>'THIS IS' + vessel name &times;3,<br>MMSI and callsign,<br>then MAYDAY + name + MMSI,<br>position,<br>nature of distress,<br>assistance required,<br>number of people on board,<br>any other useful information,<br>OVER.", "ds-vhf-distress.png"),
 ("What is a PAN-PAN used for?",
  "Urgency: a very urgent message about the safety of the vessel or a person, where there is <b>not</b> grave and imminent danger —<br>engine failure in a safe position,<br>a broken bone,<br>a dismasting with no injury,<br>or a request for medical advice.", "ds-vhf-distress.png"),
 ("What is a SÉCURITÉ message?",
  "A safety message: a navigational or meteorological warning. The Coastguard uses it to broadcast gale warnings and hazards; you would use it to report a container adrift or an unlit obstruction.", "ds-vhf-distress.png"),
 ("What is a MAYDAY RELAY?",
  "A distress message passed on behalf of another vessel that cannot transmit its own, or whose distress you have witnessed. You broadcast 'MAYDAY RELAY' three times, then 'THIS IS' your own vessel, and pass on the details.", "ds-vhf-distress.png"),
 ("What are SEELONCE MAYDAY and SEELONCE FEENEE?",
  "<b>SEELONCE MAYDAY</b> imposes radio silence on Ch 16 so distress traffic can be heard; it is normally sent by the station controlling the distress. <b>SEELONCE FEENEE</b> ends the silence and returns the channel to normal working.", "ds-vhf-distress.png"),
 ("What is Ch 16 for, and what is Ch 70?",
  "<b>Ch 16</b> is the distress, safety and calling channel, monitored by the Coastguard — keep a listening watch on it. <b>Ch 70</b> carries <b>DSC data only</b>: never transmit voice on it.", "ds-vhf-distress.png"),
 ("What is DSC and what does a distress alert send?",
  "Digital Selective Calling: a data burst on Ch 70 containing your MMSI number, the nature of distress if you have time to select it, and your GNSS position and time. It is received automatically by the Coastguard and by DSC-equipped vessels nearby. Always follow it with a voice MAYDAY on Ch 16.", "ds-vhf-distress.png"),
 ("What qualification do you need to operate a marine VHF, and what is an MMSI?",
  "The <b>Short Range Certificate</b> (SRC), and the vessel needs a Ship Radio Licence. The <b>MMSI</b> is the nine-digit Maritime Mobile Service Identity that identifies your station in DSC calls — it must be programmed correctly and registered."),
 ("List the recognised distress signals.",
  "Continuous sounding of a fog-signal apparatus;<br>a gun or explosive signal at about 1-minute intervals;<br>rockets or shells throwing red stars fired one at a time at short intervals;<br>red parachute or hand flare;<br>orange smoke;<br>SOS by any means;<br>the spoken word 'MAYDAY';<br>code flags <b>NC</b>;<br>a square flag with a ball above or below;<br>flames on the vessel;<br>slowly and repeatedly raising and lowering outstretched arms;<br>a DSC alert;<br>EPIRB, PLB or SART.", "ds-vhf-distress.png"),
 ("What do you do if you are taking on water?",
  "Get the crew into lifejackets and send a distress or urgency call early.<br>Find the source — seacocks, hoses, stern gland, log impeller, keel bolts, a holed hull — and stem it with a bung, a cushion, a sail or anything you can jam and brace in place.<br>Run all the pumps and bail.<br>Head for shallow water or a beach if you cannot control it."),
 ("What do you do if the steering fails?",
  "Take the way off.<br>Rig the <b>emergency tiller</b> on the rudder stock — know where it lives before you need it.<br>If the rudder itself is gone, balance the sails to steer, or stream a drogue or bucket on a bridle from the quarters and adjust the lines to steer.<br>If you cannot manoeuvre, <b>exhibit</b> two all-round red lights in a vertical line, or two black balls by day, for not under command, and sound one prolonged plus two short blasts in restricted visibility."),
 ("You run aground. What do you check first, and what changes depending on whether the tide is rising or falling?",
  "Check the crew, then check for damage and water ingress.<br>Stop the engine if you may have fouled something or may suck in sand.<br>Sound round the boat with a lead line or from the dinghy to find which way the deep water lies — it is often not the way you came.<br>Note whether the tide is rising or falling, because that decides everything.<br>On a <b>rising</b> tide, and on a fin keel, heel her with crew weight or the boom out to reduce draught and motor or kedge off towards the deep water; heeling a bilge-keeler or long-keeler gains you little.<br>On a <b>falling</b> tide act within seconds or prepare to sit it out: lay a kedge to hold her, pad and support the side she will lie on, close the seacocks and hatches, and get the crew somewhere safe."),
 ("What do you do if you are dismasted?",
  "Secure the crew first.<br>Stop the engine to keep rigging out of the propeller.<br>Get the rig alongside and lash it, or cut it away with bolt croppers if it is holing the hull.<br>Recover what you can for a jury rig, motor if you can, and make a PAN-PAN or MAYDAY according to the danger."),
 ("How do you take a tow?",
  "Agree the plan on VHF first.<br>Use your strongest points — round a <b>keel-stepped</b> mast, never a deck-stepped one, or through both bow fairleads to the primary winches or a substantial cleat so the load is spread — with chafe protection.<br>Keep the tow long and elastic, go slowly, and have a crew member ready with a knife at the towline.<br>Nobody stands in line with a loaded rope."),
 ("What do you need to know about a helicopter rescue?",
  "Follow the winchman's instructions exactly and only over VHF Ch 16 or as directed.<br>Lower sails if told to, keep the deck clear, secure loose gear, brief the crew, do not touch the wire until it has earthed on the deck or in the water, and never make it fast to the boat.<br>Motor a steady course as directed, usually with the wind on a bow."),
 ("What is the first thing you should do in almost any emergency?",
  "Stop, take a breath and account for your crew. Then decide whether you need outside help and call for it <b>early</b> — the situation will not get simpler, and rescue assets need time to reach you."),
 ("What is the procedure for cancelling a false or resolved distress alert?",
  "Do not just switch off. Transmit on Ch 16:<br>'All stations' &times;3,<br>'this is' + vessel name,<br>MMSI and callsign,<br>the time,<br>'cancel my distress alert of [time]' and 'out'.<br>Tell the Coastguard what happened. An uncancelled alert sends people to sea for nothing."),
 ("How do you recover a man overboard under power?",
  "Same immediate actions — shout, throw, point, MOB button.<br>Then turn <b>towards</b> the side the casualty went over, so the stern and the propeller swing away from them.<br>Approach slowly into the wind and sea so the boat lies steady, aim to stop with the casualty on the <b>leeward</b> side at the shrouds, and put the engine in <b>neutral</b>, preferably stopped, before anyone is near the hull.<br>Never approach with the casualty ahead of the bow, where you lose sight of them.", "ds-mob.png"),
 ("You have lost sight of the man overboard. What now?",
  "<b>MAYDAY immediately</b> — do not search first and call later.<br>Note the MOB waypoint and the time, and work out the datum: the casualty drifts with the tidal stream plus a little leeway, and the boat drifts faster.<br>Return down the reciprocal of your track at slow speed with every crew member searching an allocated sector, and search <b>across</b> the tide.<br>Keep passing the position and elapsed time to the Coastguard so they can compute their own drift.", "ds-mob.png"),
]),

("engine", "20 Engines", [
 ("What checks do you make before starting the engine?",
  "Engine oil level,<br>gearbox oil,<br>coolant level,<br>raw-water <b>seacock open</b>,<br>raw-water strainer clear,<br>drive belt tension and condition,<br>fuel level and no water in the filter or bowl,<br>no oil or water in the bilge under the engine,<br>gear lever in neutral,<br>and nothing loose in the engine bay."),
 ("What do you check immediately after starting?",
  "That cooling water is coming out with the exhaust,<br>that the oil pressure and alternator warning lights have gone out,<br>the exhaust note and colour,<br>and no unusual noise, smoke or vibration. No cooling water means stop the engine at once.", "fig:engine-cooling@exhaust"),
 ("What running checks do you make on passage?",
  "Temperature,<br>oil pressure,<br>battery charging,<br>cooling water flow,<br>engine note and vibration,<br>fuel remaining against hours run,<br>no smell of exhaust or fuel below,<br>and a look in the engine bay for drips, chafe or a loose belt."),
 ("What checks do you make after stopping the engine?",
  "Let it idle briefly before shutting down if it has been working hard, then stop it, and if the boat will be left,<br>close the raw-water seacock,<br>check for leaks,<br>and top up the fuel to reduce condensation. Note the hours run in the log."),
 ("How does a diesel engine's cooling system work on a yacht?",
  "Almost always <b>indirect</b>: raw sea water is drawn in through the seacock and strainer, passed by an impeller pump through a heat exchanger and then out with the exhaust, where it also cools and silences it. Fresh water and antifreeze circulate round the engine itself.", "fig:engine-cooling"),
 ("The engine overheats — what are the likely causes and what do you check first?",
  "Loss of raw-water flow: seacock shut,<br>blocked strainer or intake,<br>weed or a plastic bag on the inlet,<br>a failed <b>impeller</b>,<br>or a slipping or broken belt. Also low coolant, or a blocked heat exchanger. Stop the engine, look at whether water is coming out of the exhaust, and work back from there. Do <b>not</b> open the fresh-water header cap while the engine is hot — scalding coolant will blow out.", "fig:engine-cooling@impeller,strainer,seacock,exhaust"),
 ("Why does the engine stop or lose power, and what do you check?",
  "Almost always <b>fuel</b>: empty tank,<br>blocked pre-filter or fine filter,<br>water or diesel bug in the fuel,<br>air in the system,<br>a shut-off fuel cock,<br>or a stopped lift pump. Check the filter bowl for water and dirt, change the filter, and bleed the system."),
 ("How do you bleed air out of a diesel fuel system?",
  "Fill and refit the filters, then bleed each point in turn working from the tank towards the injectors —<br><b>pre-filter,<br>lift pump,<br>fine filter,<br>then the injection pump</b> — operating the manual lift-pump lever until fuel runs out clear and bubble-free, closing each screw before moving on. If it still will not start, slacken the injector unions <b>half a turn only</b> and crank in bursts of no more than 10 seconds, keeping hands and face clear: fuel at injection pressure can inject through skin and cause a serious injury. Many modern engines self-bleed — check the manual first."),
 ("Why must a diesel engine be bled, when a petrol engine need not?",
  "Because the injection system relies on very high pressure and cannot compress the air, so an air lock stops fuel reaching the cylinder altogether. Air gets in when the tank runs dry, a filter is changed, or a joint leaks."),
 ("What routine maintenance does a yacht diesel need?",
  "Oil and oil filter change at the manufacturer's interval,<br>fuel pre-filter and fine filter,<br>air filter,<br>impeller (carry a spare),<br>anodes in the heat exchanger,<br>drive belt,<br>coolant strength,<br>gearbox oil,<br>stern gland grease or seal check,<br>and battery terminals and electrolyte."),
 ("How do you adjust the tension of the alternator drive belt, and how tight is right?",
  "Slacken the alternator mounting and adjusting bolts, lever the alternator out, and retighten. Correct tension gives about 10 mm of deflection at the middle of the longest run when pushed firmly with a thumb. Too loose and it slips and the water pump stops; too tight and you wreck the bearings."),
 ("How do you estimate fuel consumption and range?",
  "For a small yacht diesel, a rough rule is <b>about 1 litre per hour for every 10 hp</b> at cruising revs; better still, measure your own by hours run against litres put in. Range = usable tank capacity / consumption per hour &times; speed, and never plan to use the last quarter of the tank."),
 ("What is prop walk (paddle-wheel effect), and which way does it push?",
  "<b>Paddle-wheel effect</b> (prop walk): the propeller pushes the stern sideways, most noticeably in astern. A right-handed propeller in astern walks the stern to <b>port</b>. Learn which way yours goes and use it to bring the stern in when berthing.", "fig:prop-walk"),
 ("What is 'prop wash' and how do you use it?",
  "The stream of water the propeller throws over the rudder. Ahead, it gives the rudder bite, so a brief burst of ahead power with the helm over will turn the boat even at a standstill. In astern there is no prop wash over the rudder, so steering astern needs way on."),
 ("Why should you check for lines in the water before starting the engine?",
  "Because a mooring line, sheet or MOB retrieval line round the propeller stops the engine, may damage the shaft and gland, and leaves you without power at the worst moment. It is the standard mistake in a man-overboard drill."),
 ("What is a stern gland and why check it?",
  "The seal where the propeller shaft leaves the hull. A traditional packed gland should drip slowly when running and be greased regularly; a modern lip or face seal should not drip at all. A dry traditional gland overheats; a leaking one floods the bilge."),
 ("What do black, blue and white exhaust smoke suggest?",
  "<b>Black</b> — incomplete combustion: overloading, a dirty air filter, a fouled propeller or bottom.<br><b>Blue</b> — burning lubricating oil: worn engine.<br><b>White</b> — water vapour or unburnt fuel: a cold engine, water in the fuel, or in the worst case a head gasket."),
 ("The starter turns the engine but it will not fire — what is your sequence?",
  "Check the stop control is in, the fuel cock open and the tank has fuel;<br>look for water or air in the filter;<br>feel whether the glow plugs or cold-start aid have been used;<br>check the throttle is not at idle stop;<br>then bleed the fuel system. Do not keep cranking — you will flatten the battery and fill the exhaust with fuel."),
 ("You have picked up a rope round the propeller. What do you do?",
  "Engine into neutral and stop it at once — take the key out so nobody restarts it. Sail or anchor clear of danger. Try to unwind it from on deck with a boat hook, turning the shaft by hand if you can reach it. Only go in the water in calm, sheltered conditions,<br>engine stopped and key removed,<br>tethered,<br>with someone watching,<br>and with a mask and a serrated knife — never at sea or in a stream. Otherwise anchor or take a tow and deal with it in harbour."),
 ("How do you change a raw-water impeller, and what else must you check?",
  "Shut the raw-water seacock. Undo the pump cover plate,<br>keep the gasket or O-ring,<br>and pull the impeller out with pliers or an extractor. Fit the new one the right way round with a smear of glycerine,<br>refit the cover,<br>open the seacock,<br>then start up and confirm water is coming out with the exhaust. <b>Account for every broken vane</b> — any left in the system will be jammed in the heat exchanger and will overheat you again. Carry a spare impeller, gasket and the right spanner.", "fig:engine-cooling@impeller,seacock,strainer,heat-exchanger"),
 ("What tools and spares should be aboard a cruising yacht?",
  "Impeller and gasket,<br>fuel pre-filter and fine filter,<br>engine oil and an extractor pump,<br>drive belt,<br>gearbox oil,<br>jubilee clips,<br>self-amalgamating and duct tape,<br>spare fuses and bulbs,<br>wire and terminals,<br>softwood bungs,<br>sail-repair tape,<br>needle and thread,<br>spare shackles and blocks,<br>spare line,<br>hose clips,<br>bolt croppers or a hacksaw for the rigging,<br>spanners and sockets,<br>screwdrivers,<br>mole grips,<br>a sharp knife,<br>a torch —<br>and the engine manual."),
]),

("handling", "21 Boat handling and deck work", [
 ("What are the two things that always determine how you approach a berth, buoy or anchorage?",
  "The <b>wind</b> and the <b>tide</b>, and which of the two is stronger. Approach into the stronger one so it slows you down and you keep steerage way at low speed over the ground."),
 ("How do you come alongside a pontoon under power?",
  "Assess wind and tide, and approach into the stronger of them at a shallow angle, at the slowest speed that keeps steerage. Rig fenders and lines both sides in advance,<br>brief the crew,<br>stop the boat with a burst astern,<br>and get a midships or bow line ashore first — then springs and the rest."),
 ("Which line do you get ashore first when coming alongside, and why?",
  "A <b>midships line</b>, taken to a cleat abreast of or just ahead of the boat, so it both checks the boat's way and holds her in — one line and one crew member can hold a yacht alongside while you sort out the rest. Bow and stern lines and springs follow. Never send a crew member jumping ashore with a line: step off, do not leap.", "fig:mooring-lines@fore-spring,bow-line"),
 ("How do you leave a pontoon berth with the wind pinning you on?",
  "Decide which end you want out.<br><b>Stern out:</b> keep a bow line and a bow spring — bow led to a cleat aft of you — and motor gently <b>ahead</b> against it with the helm towards the pontoon; the stern swings out, then go astern out of the berth.<br><b>Bow out:</b> keep a stern line and a stern spring — stern led to a cleat ahead of you — and motor gently <b>astern</b> against it with the helm towards the pontoon; the bow swings out, then drive ahead. Fender the pivot point and use slipped lines so nobody is left ashore.", "fig:mooring-lines@back-spring,fenders"),
 ("What is a slipped line, and why use one?",
  "A line taken round a cleat or ring ashore and back to the boat, so the crew can release it from on board without anyone going ashore. It is how you leave a berth or a buoy short-handed."),
 ("How do you pick up a mooring buoy?",
  "Work out which way the boats already on the moorings are lying, approach from downwind or down-tide into the stronger of the two, aim to arrive with just enough way to stop with the buoy at the bow, and have a crew member with a boat hook and a line rigged through the bow fairlead ready to pass through the buoy's ring or pick up the pick-up buoy."),
 ("How do you handle a boat going astern?",
  "Slowly, and expect prop walk to pull the stern one way. There is no prop wash over the rudder, so you need way on before the rudder does anything. Look astern,<br>put the helm over gently,<br>and use short bursts of power rather than continuous revs.", "fig:prop-walk@astern"),
 ("How do you turn a yacht in a confined space under power?",
  "Use a <b>standing turn</b>: helm hard over in the direction you want to turn, and <b>leave it there</b>. A short burst ahead sends prop wash over the rudder and kicks the stern round, swinging the bow. A short burst astern kills the headway — accepting that the rudder does very little astern and prop walk will dominate. Alternate short bursts and the boat pivots with almost no forward movement. Turn the way prop walk helps you, not against it.", "fig:standing-turn"),
 ("Why should you never use your hands or feet to fend off?",
  "Because a few tonnes of boat crushes fingers and legs. Use a fender or a boat hook, and if the boat is going to hit, let it hit — the gel coat is cheaper than a hand."),
 ("How do you rig a headsail correctly?",
  "Hank on or feed the luff into the foil from the tack up,<br>shackle the tack,<br>attach the halyard to the head making sure it is not twisted round the forestay,<br>lead both sheets outside the shrouds through the fairleads to the winches,<br>and put stopper knots in the ends."),
 ("What is sail trim on the different points of sailing?",
  "Close hauled — sails hard in. Close reach — eased slightly. Beam reach — about half out. Broad reach — well out. Run — right out, boom well off and the headsail goosewinged or poled out. The rule is to ease until the luff just lifts, then pull in until it stops.", "ds-points-of-sail.png"),
 ("What are the signs you are over-canvassed and should reef?",
  "Excessive heel,<br>heavy weather helm,<br>the boat slowing and slamming rather than accelerating,<br>the leeward rail down,<br>the crew uncomfortable,<br>and the helm working hard to keep her on track. If you are wondering whether to reef, reef."),
 ("How do you put a reef in with slab reefing?",
  "Head up or heave to,<br>take up on the topping lift,<br>ease the kicker and the mainsheet,<br>drop the halyard to the mark,<br>hook or pull down the luff cringle at the tack,<br>tension the halyard,<br>haul in the leech reefing line to the clew,<br>tension the foot,<br>ease the topping lift and re-set the kicker,<br>then bear away and trim."),
 ("How do you shake out a reef?",
  "In the reverse order:<br>take up the topping lift,<br>ease the halyard slightly and the reefing line,<br>free the luff cringle,<br>then hoist the halyard fully,<br>re-tension the outhaul and kicker,<br>ease the topping lift,<br>and trim. Make sure the reefing line runs free so it does not tear the sail."),
 ("How do you heave to, and why would you?",
  "Tack the boat without releasing the headsail sheet so the headsail is backed, then lash the helm to leeward and ease the mainsail. The boat lies quietly at a slow drift. Use it to reef,<br>eat,<br>sort out a problem,<br>wait for a tide or a lock,<br>or make a repair."),
 ("What is weather helm and lee helm?",
  "<b>Weather helm</b> — the boat tries to turn up into the wind, so you hold the <b>tiller to windward</b> (wheel to leeward) to keep her straight; that is where the name comes from. A little is desirable; a lot means too much mainsail or too much heel.<br><b>Lee helm</b> — she tries to turn away from the wind and you hold the tiller to leeward; it is dangerous, and usually means too much headsail or too little main."),
 ("How does a yacht behave differently under sail when you berth or anchor?",
  "You cannot stop instantly and you cannot go astern, so you must plan an approach that lets you spill wind from the sails to control speed — head-to-wind or close-reaching in — with an escape route if it goes wrong. Have the anchor ready, and know where you will bear away to if you have to abort."),
 ("What are the commands for tacking and gybing?",
  "Tacking: 'Ready about?' — crew confirm — 'Lee-oh' as you put the helm down.<br>Gybing: 'Stand by to gybe' — check the mainsheet and kicker are in and the boom controlled — 'Gybe-oh'. In both cases the point is that everyone knows what is about to happen.", "ds-points-of-sail.png"),
 ("What is an accidental gybe, and how do you avoid one?",
  "The boom crashing across uncontrolled when running or on a broad reach — it can knock someone overboard or break the rig. Avoid it by not sailing dead downwind in a seaway,<br>rigging a preventer,<br>watching the wind indicator and the helm,<br>and briefing the crew to keep their heads down when running."),
 ("What is a preventer and when do you rig it?",
  "A line from the end of the boom led forward to a strong point on the foredeck to stop the boom crossing in an accidental gybe. Rig it whenever you are running or on a broad reach, especially at night or in a swell."),
 ("How do you handle a yacht in strong wind under power?",
  "Reduce speed to keep the bow from slamming,<br>steer to take the seas at a slight angle rather than dead on,<br>expect the bow to blow off downwind at low speed,<br>allow much more room for every manoeuvre,<br>and remember you may not be able to hold a head-to-wind position at all."),
 ("What is the effect of waves on boat handling and crew?",
  "They slow the boat,<br>throw her off course,<br>make the deck dangerous<br>and cause seasickness and fatigue. Slowing down and altering course a few degrees to change the angle of encounter often transforms the ride, and a tired crew makes mistakes — plan watches and hot food."),
 ("How do you rig for a lock?",
  "Fenders both sides, long bow and stern lines ready to loop over the bollards or a ladder rung, and one crew on each. Keep the lines slipped from on board and tend them as the water level changes — never make fast solid in a rising or falling lock."),
 ("How do you go bow-to or stern-to a quay with a lazy line, Mediterranean style?",
  "Approach slowly straight in,<br>drop the anchor or pick up the lazy line at the marked point,<br>get two stern lines ashore to the quay bollards,<br>then tension the lazy line or anchor cable to hold the bow off. Have a boarding plank or ladder ready, and fenders where the neighbours are."),
 ("How do you raft up alongside another yacht?",
  "Ask permission on approach.<br>Rig fenders high and at the widest points, and approach into the stronger of wind and tide as you would a pontoon.<br>Get your bow and stern lines onto the inside boat, then run <b>your own shore lines</b> — a bow line and a stern line to the pontoon — so your weight is not hanging on your neighbour.<br>Cross their <b>foredeck</b>, never the cockpit, and stagger the masts so the rigs cannot clash in a swell.<br>Agree who is leaving when."),
 ("How do you come alongside when a tidal stream is running along the berth?",
  "Always approach <b>against</b> the stream, even if that means passing the berth and turning to come back. Head up into it at a shallow angle at the speed that gives you steerage over the ground — which can be several knots through the water while barely moving over it — and use the stream as your brake. Get the midships or upstream line ashore first. Coming alongside downstream you cannot stop, and the stream will take the bow out."),
 ("Preparing for sea: name five things you do below decks and five on deck.",
  "<b>Below:</b> stow everything so nothing can fly across in a knockdown,<br>lockers and floorboards secured,<br>heavy gear low and central,<br>washboards and hatch to hand,<br>gas off at the bottle,<br>kettle and flask filled,<br>seacocks checked,<br>bilge dry,<br>chart and plan at the chart table.<br><b>On deck:</b> sail ties and halyards clear and led,<br>sheets rove and stoppered,<br>anchor secured,<br>warps and fenders stowed and not trailing,<br>dinghy and outboard lashed,<br>jackstays rigged,<br>lifebuoy and danbuoy free to release,<br>tender painter clear of the propeller. Then walk round and look at it all again."),
]),

("passage", "22 Passage planning and victualling", [
 ("What does SOLAS Chapter V require of a small craft skipper?",
  "Regulation 34 requires you to plan the passage before you go:<br>weather,<br>tides,<br>limitations of the vessel,<br>the crew,<br>navigational dangers,<br>a contingency plan,<br>and leaving details of your intentions with someone ashore. Chapter V also requires you to carry a <b>radar reflector</b> if practicable,<br>to know the <b>lifesaving signals</b>,<br>to <b>assist anyone in distress</b> at sea,<br>to <b>report dangers to navigation</b>,<br>and not to misuse distress signals.", "ds-passage-planning.png"),
 ("List the elements of a passage plan.",
  "Weather forecast and how you will update it;<br>tidal heights and streams and any tidal gates;<br>limitations of the vessel (draught, air draught, fuel and water range, gear);<br>the crew's experience, fitness and hours of darkness;<br>navigational dangers;<br>a contingency plan with bolt holes;<br>and information ashore.", "ds-passage-planning.png"),
 ("What is a bolt hole and why does every leg need one?",
  "A port or anchorage you can divert to if the weather, the crew or the boat changes the plan. Identify it in advance with its approach, its tidal restrictions and the conditions in which it is usable, because you will be choosing it when you are tired and it is dark."),
 ("What do you leave with someone ashore?",
  "Your destination and route,<br>ETA,<br>the boat's name, description and sail number,<br>the number of people aboard,<br>your contact details and safety equipment,<br>and clear instructions on what to do — and what <b>not</b> to do — if you are overdue. Then tell them when you arrive."),
 ("How do you work out an ETA for a passage leg?",
  "Distance divided by expected speed over the ground for each leg, allowing for the tide hour by hour and for a realistic boat speed rather than your best ever. Add contingency time, and check the arrival time against the tidal window at the destination."),
 ("How do you plan a passage around tidal gates?",
  "Work backwards from the gate. Decide the time you must be at each gate (a headland at slack water,<br>a bar on a rising tide,<br>a lock or sill within its window), then compute the departure time from the passage times between them. If the gates do not line up, the passage does not work — change the day."),
 ("What are the limitations of the vessel that should shape a plan?",
  "Draught and air draught,<br>fuel and water capacity and range under power,<br>the sail wardrobe and reefing arrangements,<br>the state of the gear,<br>whether you have self-steering,<br>the navigation and communications kit,<br>how she behaves in a head sea,<br>and whether she can be sailed short-handed if someone is out of action."),
 ("How do you plan a watch system for a short-handed crew on a night passage?",
  "Keep watches short enough to stay alert — typically 2 to 3 hours at night — with a clear handover briefing covering position,<br>course,<br>traffic,<br>weather and any changes. Make sure everyone gets sleep before as well as during, and that the skipper is not the only person who can navigate."),
 ("What should you brief the crew on before a passage?",
  "The plan and the ETA;<br>the weather;<br>who does what and the watch system;<br>lifejackets, harnesses and clipping points;<br>MOB drill;<br>how to send a distress call and where the position is displayed;<br>seacocks, bilge pumps, gas, heads and galley;<br>fire extinguishers and the liferaft;<br>and the rule that anyone can raise a concern at any time."),
 ("What is victualling, and what does a Day Skipper need to think about?",
  "Provisioning for the passage: enough food and, above all, <b>water</b> for the planned trip plus a margin for delay;<br>food that can be prepared and eaten in a seaway (one-pot meals, sandwiches, soup in a flask made before you leave);<br>hot drinks;<br>snacks in the cockpit;<br>and allowance for seasickness reducing appetite while dehydration rises."),
 ("Why make food and hot drinks before you leave harbour?",
  "Because cooking in a lumpy sea is difficult, dangerous and the fastest route to seasickness. A flask of soup or stew prepared alongside keeps a cold night watch functioning."),
 ("What documents should be aboard for a cross-Channel passage?",
  "Passports for everyone,<br>the ship's registration and Ship Radio Licence,<br>evidence of VAT status and insurance,<br>the skipper's certificate of competence and SRC,<br>a crew list,<br>and — for France and some other countries — an ICC or national equivalent. Check the current entry requirements before you go."),
 ("Arriving in the UK from abroad: when does the Q flag go up, and how do you report?",
  "Arriving in the UK from outside the UK — the Channel Islands included — you must fly the plain yellow <b>Q</b> flag as soon as you enter UK waters, the 12-mile limit, and keep it up until reporting is complete; failing to do so is a penalty offence. Report through Border Force's <b>sPCR</b> online service, or the C1331 fallback; outbound voyages are notified 2 to 24 hours before departure. Arrivals into Northern Ireland from an EU state need no Q flag. These rules change — check the current gov.uk guidance for both countries before you sail."),
 ("How do you decide on the day whether to go?",
  "Compare the actual forecast with the limits of boat, crew and passage;<br>check the tidal windows still work;<br>look at wind against tide and at the state of the entrance you are leaving and the one you are arriving at;<br>and consider what happens if the wind is 10 knots more than forecast. The decision to stay in port is a seamanlike decision, not a failure."),
 ("What do you write in the deck log, and why does it matter?",
  "Time,<br>position,<br>log reading,<br>course steered,<br>speed,<br>wind and weather,<br>barometer,<br>and events —<br>sail changes,<br>engine hours,<br>fixes,<br>incidents. It is the raw material for a dead reckoning if the electronics die, and it is the record if anything goes wrong."),
 ("Preparing for a night passage: what do you do about the navigation lights, your night vision, and the watch?",
  "Do the pilotage plan and all the chartwork in daylight. Check every navigation light and carry spare bulbs; check torches, headtorches and batteries. Set instrument lights to red and keep white deck lights off to protect night vision — 20 minutes to recover it, seconds to lose it. Everyone in lifejackets,<br>clipped on before leaving the cockpit,<br>and nobody on deck alone. Hot food and a flask made before dark,<br>the watch system briefed,<br>and the log kept every hour so a DR can be started at any moment."),
 ("How do you register your passage details with the Coastguard?",
  "You do not — the old CG66 voluntary safety identification scheme was withdrawn. Instead leave your plan with a responsible person ashore, or use the free <b>RYA SafeTrx</b> app, which records your intended passage and ETA and alerts your emergency contact if you are overdue. Whichever you use, tell them what to do — and what <b>not</b> to do — if you fail to arrive, and always tell them when you get in."),
]),

("electronics", "23 Electronic navigation", [
 ("How does GNSS work, in one sentence?",
  "The receiver measures the time signals from several satellites take to reach it and computes its position from the ranges; four or more satellites give position, altitude and a very accurate time."),
 ("What are the practical limitations of GNSS?",
  "It can be lost or degraded by antenna failure,<br>power failure,<br>jamming or spoofing, and it tells you where you are, not what is around you. Accuracy of a few metres is meaningless if the <b>chart</b> or the datum is less accurate, and the receiver will happily give a position it has interpolated."),
 ("Why can a GNSS position and a paper chart disagree?",
  "Because of the horizontal <b>datum</b>. GNSS works in WGS84; older charts may use a local datum, and the shift can exceed 100 m. Set the receiver to the chart's datum or apply the correction printed on the chart."),
 ("What is a waypoint, and how should you place them?",
  "A position stored in the receiver as a target or a route point. Place them in safe water, not on a buoy or a hazard — never steer straight at a buoy, since everyone else's plotter has it as a waypoint too. Offset them to one side of the mark."),
 ("What are COG and SOG, and how do they differ from heading and log speed?",
  "<b>Course over ground</b> and <b>speed over ground</b> come from the GNSS and include the tide. <b>Heading</b> comes from the compass and <b>log speed</b> from the paddlewheel or ultrasonic log, through the water. Comparing them tells you what the tide is doing."),
 ("What is 'bearing to waypoint' versus 'course to steer'?",
  "The plotter's <b>bearing to waypoint</b> is the direct line from where you are now to the waypoint; it does not allow for tide. A <b>course to steer</b> allows for the tidal stream so you make good the intended track. Steering the bearing to waypoint in a cross-tide sails you round a curve."),
 ("What does an echo sounder actually measure, and what can fool it?",
  "The time for an ultrasonic pulse to return from the bottom. It can be fooled by a shoal of fish,<br>a dense layer of weed or plankton,<br>aeration under the hull from a wave or a turn,<br>and soft mud giving a reading either above or below the true bottom. It also reads from the transducer, not the keel."),
 ("What is a lead line, and why would you use one?",
  "A weighted line marked in metres or fathoms, swung ahead and let touch the bottom. It needs no power,<br>works when the sounder fails,<br>tells you the nature of the bottom if the lead is armed with tallow,<br>and is the right tool for sounding out of a dinghy round an unfamiliar anchorage."),
 ("How does a log measure speed and distance, and what goes wrong?",
  "A paddlewheel, impeller or ultrasonic transducer through the hull, calibrated to read speed and to totalise distance. Paddlewheels foul with weed and barnacles and then under-read badly. Check it against GNSS in still water, and know how to clear it — with the bung ready."),
 ("What can small-craft radar do for you, and what are its limits?",
  "It gives range and bearing of targets and of the coastline in poor visibility, and CPA if it has a plotting function. Limits: a small yacht's scanner is low, so range is short;<br>sea clutter and rain hide small targets;<br>targets in a blind sector behind the mast disappear;<br>and interpreting it takes practice, which is why a radar course is worth doing."),
 ("What is AIS, and what does it not show you?",
  "Ships broadcast identity,<br>position,<br>course,<br>speed and more over VHF; a receiver shows them with CPA and TCPA. It does <b>not</b> show vessels without AIS — most yachts,<br>fishing boats,<br>and anything with it switched off — and it does not show rocks."),
 ("What is a chart plotter's biggest single danger to a navigator?",
  "It shows a small window round the boat symbol, so the wider picture and what lies just off the route disappears. Zoom out regularly, keep a paper chart of the whole passage, and never let the plotter replace thinking about where the dangers are."),
 ("What is NAVTEX?",
  "An automatic text receiver on 518 kHz that prints or displays navigational warnings, weather forecasts and search and rescue information for the area, with no need to be listening at a particular time."),
 ("Why should you cross-check electronic position with an independent method?",
  "Because a single-source position has no error check. Compare the GNSS with a visual fix, a transit, a depth contour or a light bearing. Two independent methods agreeing is a position; one method is an assumption."),
 ("What is the electrical failure plan on a modern yacht?",
  "Know which instruments are on which circuit and where the breakers and fuses are,<br>carry spare fuses,<br>keep the handheld VHF and handheld GNSS charged in the grab bag,<br>keep a paper chart, almanac, plotting instruments, watch and hand-bearing compass at the chart table,<br>and log positions regularly so a DR can be started from the last known one."),
]),

("environment", "24 Environment, rules and responsibilities", [
 ("What are the skipper's basic legal responsibilities?",
  "The safety of the vessel and everyone aboard;<br>compliance with the IRPCS, local byelaws and the law of the country you are in;<br>keeping the vessel seaworthy and properly equipped;<br>not going to sea in a manner that endangers others;<br>and rendering assistance to anyone in distress at sea."),
 ("What must you do if you receive a distress call?",
  "You are obliged to render assistance to persons in distress at sea if you can do so without serious danger to your own vessel or crew. Acknowledge, report to the Coastguard, and proceed if you can help. Do not assume someone else has answered."),
 ("What may you not discharge overboard?",
  "Oil and oily mixtures, and any garbage other than food waste, are prohibited; plastics are banned absolutely. Sewage discharge is regulated and prohibited in many harbours and marinas — use pump-out facilities where they exist. Chemical toilet contents, oil and old antifouling go ashore."),
 ("What is MARPOL Annex V in practice for a yacht?",
  "Nothing goes over the side except food waste, and only offshore: <b>comminuted</b> food waste, through a 25 mm screen, not less than <b>3 miles</b> from land; uncomminuted not less than <b>12 miles</b>, and 12 miles inside a Special Area. Everything else —<br>plastics,<br>packaging,<br>cans,<br>glass,<br>oily rags,<br>filters,<br>batteries,<br>flares<br>— comes back ashore for disposal at the marina's facilities. Boats of 12 m and over must display a placard of the rules."),
 ("What should you do with out-of-date flares?",
  "Never fire them for fun,<br>never put them in a bin,<br>and never leave them at a police or fire station — that is illegal dumping. <b>HM Coastguard no longer accepts flares for disposal.</b> Try the supplier you bought them from,<br>a liferaft service agent,<br>your harbour or marina,<br>a registered disposal point on The Green Blue's environmental facilities map,<br>a flare amnesty,<br>or a specialist hazardous-waste contractor for a fee. Disposal is the owner's legal responsibility, so check what is available <b>before</b> you buy new ones."),
 ("How should you avoid damaging the seabed when anchoring?",
  "Avoid anchoring on seagrass beds, maerl and other protected habitats, which chain scours badly; use the designated eco-moorings where they exist; and check the chart and local guidance for protected areas before you drop."),
 ("What is your responsibility about wash and speed?",
  "Your wash is your responsibility. Slow down past moorings,<br>dredgers,<br>works,<br>small craft,<br>rowers,<br>swimmers and anyone working on a boat, and observe harbour speed limits — usually 6 knots or less, and often measured over the ground."),
 ("How should you behave around marine wildlife?",
  "Do not chase, encircle or separate animals;<br>keep a steady slow course and let them approach you;<br>avoid seal haul-outs and nesting seabird colonies, especially in the breeding season;<br>and give whales and dolphins a wide, predictable berth."),
 ("What is antifouling and what care does it need?",
  "A coating that stops weed and barnacles growing on the hull. It contains biocides, so scrape and sand it only where there is proper containment ashore, wear protection, and never let residues go into the water."),
 ("What insurance and registration should a cruising yacht have?",
  "Third-party liability insurance at the minimum, and usually full cover; many marinas and foreign authorities require proof. Registration (Part 1 or the Small Ships Register) is needed to prove nationality abroad, and a Ship Radio Licence is required for the VHF."),
 ("What is the ICC and when do you need it?",
  "The International Certificate of Competence, issued in the UK by the RYA, is proof of competence recognised by many countries for their inland and coastal waters. It is not needed in UK waters but is often required or requested abroad, and can be obtained on the strength of a Day Skipper practical certificate."),
 ("What does the RYA Day Skipper practical certificate actually say you can do?",
  "That you have been assessed as able to skipper a 30 to 45 ft cruising yacht and its crew safely <b>by day, on day trips, in familiar waters</b> — doing your own pilotage, navigation, boat handling and passage planning. A certificate gained in non-tidal waters is endorsed as such. It is not a licence, and it is not a Yachtmaster."),
 ("What are the prerequisites for the RYA Day Skipper practical course?",
  "Basic sailing ability plus <b>5 days at sea, 100 miles logged and 4 night hours</b> aboard a sailing yacht, and navigation and theory to <b>Day Skipper shorebased standard</b> — the shorebased certificate itself is not compulsory. Minimum age <b>16</b>. The course runs as 5 days,<br>3 weekends,<br>or 3 days plus 2."),
 ("What does the Day Skipper shorebased course cover and how long is it?",
  "About 40 hours plus exam time:<br>seamanship,<br>coastal navigation and pilotage,<br>chartwork,<br>electronic charts,<br>position fixing,<br>plotting a course to steer,<br>weather and meteorology,<br>tides,<br>and the collision regulations. It is assessed by written papers, with chart 5011, an exercise chart and an almanac extract to hand."),
]),
]
