# -*- coding: utf-8 -*-
"""RYA Day Skipper cards, part A: seamanship foundations, safety, IRPCS, lights, sound.

Each section is (key, deck_suffix, [cards]). A card is (front, back) or
(front, back, image_filename). No tabs or newlines inside a field.
"""

SECTIONS_A = [
("terms", "01 Boat and nautical terms", [
 ("Bow, stern, port, starboard — what does each mean?",
  "<b>Bow</b> = the front.<br><b>Stern</b> = the back.<br><b>Port</b> = the left side facing forward (red).<br><b>Starboard</b> = the right side facing forward (green).", "fig:hull-plan@bow,stern,port,starboard"),
 ("Amidships",
  "The middle of the boat, both fore-and-aft and athwartships.", "fig:hull-plan@amidships,bow,stern"),
 ("Beam (two meanings)",
  "1. The widest part of the hull, and so the boat's width.<br>2. A direction at right angles to the fore-and-aft line: 'abeam'.", "fig:hull-plan@beam"),
 ("Draught",
  "The vertical distance from the waterline to the lowest point of the keel — the minimum depth of water the boat needs.", "fig:hull-profile@draught,waterline"),
 ("Air draught",
  "The height from the waterline to the highest point of the boat, usually the masthead including the aerial. What matters for bridges and overhead cables.", "fig:hull-profile@air-draught,waterline"),
 ("Freeboard",
  "The vertical distance from the waterline to the deck edge.", "fig:hull-profile@freeboard,waterline"),
 ("Windward and leeward",
  "<b>Windward</b> is the side or direction the wind is coming from (also 'weather side'). <b>Leeward</b> ('loo-ard') is the side or direction the wind is going to — the sheltered side. On a sailing boat the leeward side is the boom's side.", "fig:windward-lee@wind,windward,leeward"),
 ("Lee shore — and why it matters",
  "A shore onto which the wind is blowing. It is dangerous: the wind and waves push you towards it, and it gives no shelter. A weather shore, with the wind blowing off it, is the sheltered one.", "fig:windward-lee@wind,lee-shore,weather-shore"),
 ("Ahead, astern, abeam, abaft, forward of the beam",
  "<b>Ahead</b> in front. <b>Astern</b> behind. <b>Abeam</b> at 90&deg; to the fore-and-aft line. <b>Forward of the beam</b> anywhere in the 90&deg; from ahead to abeam. <b>Abaft the beam</b> anywhere from abeam to astern.", "fig:bearings@ahead,astern,abeam,forward-beam,abaft-beam"),
 ("Which direction is 22.5&deg; abaft the beam, and why does the number matter?",
  "It is 112.5&deg; from ahead — the after cut-off of each sidelight and the boundary of the overtaking sector. Both sidelights together cover 225&deg;, matching the masthead light arc; the sternlight covers the remaining 135&deg;.", "fig:bearings@abaft-22,abeam,ahead"),
 ("Heel versus list",
  "<b>Heel</b> is a temporary lean caused by wind or crew weight. <b>List</b> is a permanent lean caused by unbalanced weight or flooding."),
 ("The three rotational motions of a boat at sea",
  "<b>Roll</b> — side to side about the fore-and-aft axis.<br><b>Pitch</b> — bow and stern rising and falling.<br><b>Yaw</b> — swinging left and right of the heading.", "fig:motions"),
 ("Displacement",
  "The weight of water the hull displaces, which equals the boat's total weight. A displacement hull is limited to a hull speed of roughly 1.34 &times; &radic;(waterline length in feet) in knots."),
 ("What makes a cruising yacht stable?",
  "The keel puts the centre of gravity low. When the boat heels, the centre of buoyancy moves outboard, so gravity and buoyancy form a <b>righting moment</b> that pushes her upright. Beyond the angle of vanishing stability that moment reverses and she will capsize."),
 ("Reserve buoyancy",
  "The watertight volume above the waterline. It provides the extra buoyancy that lifts the boat over waves and resists swamping — one reason for closing hatches and washboards at sea."),
 ("What happens to stability if you fill the water tanks and load the anchor locker?",
  "Weight low down (tanks, keel, batteries) improves stability. Weight high up or far forward (anchor and chain in the bow, gear on deck, crew on the coachroof) raises the centre of gravity, reduces stability and makes the boat pitch harder. Free surface in a part-full tank also reduces stability."),
 ("Name the three sides and three corners of a mainsail.",
  "Sides: <b>luff</b> (leading edge), <b>leech</b> (trailing edge), <b>foot</b> (bottom).<br>Corners: <b>head</b> (top), <b>tack</b> (bottom forward), <b>clew</b> (bottom aft).", "fig:sail-parts@head,tack,clew,luff,leech,foot"),
 ("Standing rigging versus running rigging",
  "<b>Standing rigging</b> is fixed and holds the mast up: forestay,<br>backstay,<br>shrouds,<br>spreaders,<br>chainplates.<br><br><b>Running rigging</b> moves and controls the sails: halyards,<br>sheets,<br>reefing lines,<br>kicker,<br>topping lift,<br>cunningham,<br>outhaul.", "fig:rigging"),
 ("Halyard versus sheet",
  "A <b>halyard</b> hoists a sail (pulls it up). A <b>sheet</b> trims a sail (pulls it in or lets it out).", "fig:rigging@halyard,sheet"),
 ("Kicker (boom vang) — what does it do?",
  "It pulls the boom down, controlling leech tension and stopping the boom lifting when the sail is eased. Without it the mainsail twists open and loses drive off the wind.", "fig:rigging@kicker"),
 ("Topping lift",
  "A line from the masthead to the end of the boom that holds the boom up when the mainsail is lowered or reefed.", "fig:rigging@topping-lift"),
 ("Genoa versus jib",
  "Both are headsails. A <b>jib</b>'s clew does not reach past the mast; a <b>genoa</b> overlaps the mast and is larger. A furling headsail can be partly rolled to reduce area."),
 ("What is a seacock and why must you know where they all are?",
  "A valve on a hull fitting below or near the waterline (engine cooling intake, heads, sinks, log). They are your first defence against flooding, so every crew member should know their location and how to shut them, and softwood bungs should be stowed nearby."),
 ("Bilge, sole, bulkhead",
  "<b>Bilge</b> — the lowest internal space where water collects.<br><b>Sole</b> — the cabin or cockpit floor.<br><b>Bulkhead</b> — a transverse structural partition."),
 ("Pulpit, pushpit, stanchions, guardrails, jackstay",
  "<b>Pulpit</b> — the rail at the bow.<br><b>Pushpit</b> — the rail at the stern.<br><b>Stanchions</b> — the posts supporting the <b>guardrails</b> along the deck.<br>A <b>jackstay</b> is a wire or webbing line running fore and aft that you clip a harness tether to.", "fig:deck-fittings@pulpit,pushpit,stanchions,guardrails,jackstay"),
 ("Warp, spring, breast line",
  "<b>Warps</b> are mooring lines: bow line and stern line run forward and aft. <b>Springs</b> run at a shallow angle to stop fore-and-aft movement. <b>Breast lines</b> run at right angles to hold the boat in to the pontoon.",
  "fig:mooring-lines@bow-line,stern-line,fore-spring,back-spring,breast-line"),
 ("What is a transit?",
  "Two identifiable objects seen in line. It gives a position line with no compass error at all, and shows instantly whether you are being pushed off it — the single most reliable pilotage tool."),
 ("Cable (as a unit)",
  "One tenth of a nautical mile, so about 185 metres. Also the collective word for the anchor chain or warp."),
 ("Fathom",
  "Six feet, about 1.83 m. Old charts are in fathoms and feet; modern metric charts are in metres. Always check the chart's depth units."),
 ("Fenders, fairleads, cleats and bollards",
  "A <b>fender</b> cushions the hull. A <b>fairlead</b> guides a line and takes the chafe. A <b>cleat</b> or <b>bollard</b> is what you make the line fast to. Never lead a warp over a sharp edge.", "fig:deck-fittings@cleat,fairlead"),
 ("Keel types and what each means for you",
  "<b>Long keel</b> — tracks well, turns slowly, sits upright when dried out.<br><b>Fin keel</b> — fast and manoeuvrable, less directional stability, needs support to dry out.<br><b>Bilge keels</b> — shallower draught, will dry out level, slower to windward.<br><b>Lifting keel or centreboard</b> — variable draught.<br><b>Wing keel</b> — shallower with a bulb for stability."),
 ("What does 'make fast', 'belay', 'surge' and 'snub' mean?",
  "<b>Make fast</b> / <b>belay</b> — secure a line.<br><b>Surge</b> — let a line slip in a controlled way round a winch or cleat.<br><b>Snub</b> — check a running line sharply to take the load."),
 ("Riding turn",
  "A turn of rope trapped over itself on a winch drum so it will not release. Take the load off with a rolling hitch onto a spare line, then clear it."),
 ("Chafe — why is it the thing that actually breaks mooring lines?",
  "A rope under load moving over any edge wears through from the outside, often overnight and unseen. Use fairleads, chafe sleeves or a length of hose, and inspect lines where they pass over the toe rail."),
]),

("ropework", "02 Ropework and knots", [
 ("Figure of eight — use",
  "A stopper knot in the end of a sheet or halyard so it cannot run out through a block or fairlead.", "ds-knots-ropes.png"),
 ("Bowline — use",
  "Makes a fixed loop that will not slip and can be untied after loading. Used to attach a sheet to a clew, drop a loop over a post, or make a temporary loop anywhere.", "ds-knots-ropes.png"),
 ("Clove hitch — use and limitation",
  "Attaches a line to a rail, post or ring — the classic fender lanyard knot. It can slip or work loose under a varying or uneven load, so it is not for a load-bearing mooring line."),
 ("Round turn and two half hitches — use",
  "Secures a mooring line to a ring, post or bollard. The round turn takes the load, so it can be tied and untied while the line is under tension."),
 ("Rolling hitch — use",
  "Grips along another rope or a spar. The standard fix for a riding turn on a winch or a jammed sheet: tie it to the loaded line and lead it to another winch to take the strain."),
 ("Reef knot — correct use and the trap",
  "Joins the two ends of the <b>same</b> line of equal diameter — tying in a reef, a sail tie, a lashing. It is <b>not</b> a knot for joining two ropes under load: use a sheet bend or a double sheet bend."),
 ("Sheet bend and double sheet bend",
  "Join two ropes together. Use the <b>double</b> sheet bend when the ropes differ in size or are slippery — the extra turn stops the thinner one pulling through."),
 ("Which knot for a jib sheet to the clew of a headsail?",
  "A bowline. It holds securely under load and, unlike most knots, can still be undone afterwards."),
 ("What are the three parts of a rope you name when tying knots?",
  "The <b>standing part</b> (the loaded main length),<br>the <b>bight</b> (a bend or loop in it),<br>and the <b>working end</b> (the end you tie with). The extreme end is the <b>tail</b>; strictly, the <b>bitter end</b> means the inboard end of the anchor cable, made fast at the bitts."),
 ("Polyester (Terylene / Dacron) — properties and use",
  "Low stretch, good UV and abrasion resistance, sinks, holds its strength when wet. The standard rope for sheets and halyards.", "ds-knots-ropes.png"),
 ("Nylon (polyamide) — properties and use",
  "Very strong and stretchy, so it absorbs shock loads. Used for mooring lines and anchor warps. It loses roughly 10-15% of its strength when wet and degrades in UV."),
 ("Polypropylene — properties and use",
  "Cheap, light, and it floats. Poor UV resistance and comparatively low strength, so it is for heaving lines, dinghy painters and lifebuoy lines, not for load-bearing work."),
 ("Aramid and HMPE (Dyneema, Spectra) — properties and use",
  "Extremely strong for their weight with almost no stretch, but expensive and slippery. Used for racing halyards, high-load running rigging and soft shackles."),
 ("Why whip or heat-seal a rope's end?",
  "To stop the rope unlaying or the braided cover milking off the core. A whipping is the seamanlike job; a heat-seal is quicker but brittle."),
 ("How much strength does a knot cost you?",
  "A knot puts a tight bend in the fibres and can cut a rope's breaking strength by roughly 30-50% — a bowline is often quoted at about 40% loss. A properly made splice loses much less, typically under 10%."),
 ("Care of synthetic rope",
  "Rinse off salt in fresh water,<br>dry before stowing,<br>keep out of sunlight,<br>avoid sharp bends and chafe,<br>never stand on a rope,<br>and retire it when the cover is furred or the core is stiff and glazed."),
 ("How do you coil rope so it runs cleanly?",
  "Laid (three-strand) rope is coiled clockwise with a slight twist in each turn. Braided rope prefers a figure-of-eight flake, which puts in no twist. A rope that has been coiled the wrong way will kink and jam in a block."),
 ("Which knot takes the load off a jammed, loaded sheet?",
  "A rolling hitch on the loaded line, led to a spare winch or cleat. Then you can clear the original turn safely."),
]),

("anchoring", "03 Anchoring", [
 ("How do you choose an anchorage?",
  "Shelter from the wind now <b>and</b> after the forecast change;<br>good holding ground;<br>enough depth at low water and swinging room at all states of tide;<br>out of the fairway, cables and prohibited areas;<br>moderate tidal stream;<br>and an easy exit if the weather turns. A lee shore is not shelter.", "ds-anchoring.png"),
 ("How much scope do you let out?",
  "As a working rule, <b>4 times the maximum depth for all chain</b> and <b>6 times for rope with a chain leader</b>. Increase it in strong wind, swell or poor holding. Calculate from the depth at high water, not the depth when you arrive.", "ds-anchoring.png"),
 ("What depth do you use to work out scope?",
  "The <b>maximum</b> depth you will see while anchored — charted depth plus the height of tide at the <b>highest high water during your whole stay</b>, plus the height of the bow roller above the water. Then check that the <b>minimum</b> depth, at the lowest low water, still clears your keel."),
 ("Good and bad holding ground",
  "Good: firm sand, mud and clay.<br>Poor: rock, shingle, and especially weed, which stops the anchor reaching the bottom.<br>The chart's seabed abbreviations tell you: S sand,<br>M mud,<br>Cy clay,<br>R rock,<br>Wd weed,<br>Sh shells,<br>G gravel,<br>St stones."),
 ("Describe the anchoring drill.",
  "Brief the crew and prepare the anchor and cable.<br>Motor slowly up-wind or up-tide to the chosen spot and stop over the ground.<br>Lower the anchor as the boat starts to make way astern, paying out cable steadily so it lays in a line.<br>Snub the cable, then go gently astern to dig the anchor in.<br>Check the holding on transits or bearings, log the position and depth, and show the correct signal.", "ds-anchoring.png"),
 ("Why lower the anchor rather than throw it, and why with the boat moving astern?",
  "Throwing it piles the chain on top of the anchor and fouls it. Making way astern lays the cable out in a straight line so the anchor gets a horizontal pull and digs in instead of skipping."),
 ("How do you check the anchor is holding?",
  "Take two transits ashore, or a couple of bearings, and watch them: if they stay put you are holding. Feel the cable — a dragging anchor sends a juddering vibration up it. Set a GNSS anchor alarm as a back-up, never as the only check."),
 ("Signals for a vessel at anchor",
  "By day, one <b>black ball</b> forward.<br>By night, an <b>all-round white light</b> where it can best be seen; a vessel of 50 m or more shows two, the forward one higher. Vessels under 7 m are exempt unless anchored in or near a channel, fairway, anchorage or where other vessels normally navigate."),
 ("Sound signal for a vessel at anchor in restricted visibility",
  "Rapid ringing of the bell for about 5 seconds at intervals of not more than one minute. A vessel of 100 m or more also sounds a gong aft. She may in addition sound one short, one prolonged and one short blast to warn an approaching vessel."),
 ("How do you weigh anchor?",
  "Motor slowly up towards the anchor as the crew recovers the cable, so the engine does the work, not the windlass or the crew. When the cable is up and down, break the anchor out,<br>wash off the mud,<br>and stow and secure it before you leave."),
 ("The anchor is fouled and will not come up — what can you do?",
  "Take a turn of the cable on a cleat and use the boat's buoyancy in a swell, or motor slowly over it from a different direction to break it out. An anchor buoy and tripping line rigged to the crown before you anchor is the real answer in a known foul anchorage."),
 ("CQR or plough anchor",
  "A hinged plough. A good all-rounder that holds well in mud and sand, but it can be slow to set and needs weight to bury."),
 ("Danforth or Fortress anchor",
  "Twin flat flukes. Excellent holding in sand and mud for its weight and it stows flat, but it performs poorly in weed and can trip and skip if the pull changes direction."),
 ("Bruce or claw anchor",
  "Sets very readily and resets well after a wind shift, but has lower holding power for its weight and is awkward to stow."),
 ("Modern scoop anchors (Rocna, Spade, Vulcan, Excel)",
  "Concave-fluke, weighted-tip or roll-bar designs that set fast and give very high holding power for their weight. Now the common choice for cruising yachts. The <b>Delta</b> is <b>not</b> one of these: it is a fixed-shank, convex-fluke plough, a good all-rounder that sets more reliably than a CQR."),
 ("Fisherman anchor",
  "Traditional stock-and-fluke design. The one anchor that reliably hooks into rock and heavy weed, but it has low holding in sand and mud and is awkward to stow."),
 ("Why is chain better than rope for anchoring?",
  "Its weight makes the cable hang in a curve (catenary) so the pull on the anchor stays horizontal and shock loads are absorbed, and it resists chafe on the seabed. Rope is lighter and cheaper but needs more scope and a chain leader at the anchor end."),
 ("What is a swinging circle and how big is it?",
  "The circle the boat can sweep as the wind or tide turns her: radius = the scope let out plus the length of the boat. Check it clears other boats, moorings and shallow water at all states of tide, and remember boats on chain and on rope swing differently."),
 ("Anchoring in a strong tidal stream with a wind against it",
  "Boats will lie to the stronger of the two, and may sheer about. Allow more scope,<br>more swinging room,<br>keep a watch,<br>and expect the boat to lie across the wind. Consider a second anchor laid astern, or move to a better berth."),
 ("Why keep an anchor watch?",
  "Because an anchor that has held for six hours can break out the moment the tide turns or the wind rises. Watch transits and depth, keep the engine ready, and know your escape route in the dark before you need it."),
 ("What is a kedge anchor for?",
  "A second, lighter anchor. Use it to lay out astern to stop the boat swinging,<br>to hold her off after grounding,<br>to haul off a lee shore,<br>or as a spare if the main anchor is lost or fouled. It is usually laid from the dinghy, or carried out and dropped clear."),
]),

("safety", "04 Safety equipment and fire", [
 ("What safety brief should every new crew member get before you leave?",
  "Where the lifejackets, harnesses and clipping points are and how to fit them;<br>where the flares, fire extinguishers, fire blanket, first aid kit, liferaft and grab bag are;<br>how to work the heads, gas and galley;<br>how to send a VHF distress alert;<br>the MOB drill;<br>the location of seacocks and bilge pumps;<br>and who does what on deck."),
 ("Lifejacket or buoyancy aid: what is the difference, and what rating do you want for cruising?",
  "A <b>lifejacket</b> — 100 N is the lowest lifejacket level, for sheltered water with prompt rescue at hand; 150 N for coastal and offshore use; 275 N for extreme conditions or heavy clothing — is designed to turn an unconscious wearer face-up and support them. A <b>buoyancy aid</b> is <b>50 N</b>, inshore, and only helps a conscious person stay afloat: it will <b>not</b> turn an unconscious person face-up. Cruising calls for at least 150 N, with a crotch strap, light, whistle, spray hood and preferably an AIS beacon or PLB."),
 ("When should the crew wear lifejackets and harnesses?",
  "Whenever the skipper says so — and as a minimum at night,<br>in poor visibility,<br>in rough weather,<br>when reefing or working on deck,<br>in a dinghy,<br>and for non-swimmers and children. Clip on before you leave the cockpit at night."),
 ("What is a danbuoy for?",
  "It marks a man overboard with a visible flag on a weighted pole, often with a light, drogue and horseshoe lifebuoy. It gives the helm something to steer back to — a head in the water is almost invisible at any distance."),
 ("Red parachute rocket flare, red hand flare, orange smoke, white flare — what is each for?",
  "<b>Red parachute rocket</b> — distress, to attract attention over the horizon at night, burns high for about 40 seconds.<br><b>Red hand flare</b> — distress, to pinpoint your position for a rescuer who is already close.<br><b>Orange smoke</b> — distress by day, best for aircraft and helicopters.<br><b>White flare</b> — <b>not</b> a distress signal: it warns another vessel of your presence to avoid collision.", "fig:flares"),
 ("How do you fire a hand flare, and how do you fire a parachute rocket?",
  "Read the instructions in daylight, before you need them. <b>Hand flare or smoke:</b> hold it at arm's length over the side on the <b>downwind, leeward</b> side, angled away from you, the boat and the rig, gloves on, and do not look at it. <b>Parachute rocket:</b> stand with your back to the wind and fire it near vertically, angled about 15&deg; downwind in strong wind — never held out over the water, and never near the rig or the liferaft. Under low cloud a rocket disappears into the cloud, so use a hand flare instead. Never let anyone look down the tube.", "fig:flares@handheld,parachute"),
 ("What fire extinguishers should a cruising yacht carry, and where?",
  "At least two multi-purpose dry powder extinguishers stowed by the exits — typically one at the companionway and one at the forward end of the accommodation — plus a <b>fire blanket</b> in the galley and ideally an automatic or port-fed extinguisher for the engine compartment. Check the gauges and service dates."),
 ("How do you fight a galley fat fire?",
  "Turn off the gas at the bottle or isolator, smother the pan with a <b>fire blanket</b>, and leave it covered to cool. Never use water on burning fat and never carry a burning pan through the boat."),
 ("How do you fight an engine compartment fire?",
  "Stop the engine, shut off the fuel, and discharge the extinguisher through the dedicated port <b>without</b> opening the compartment — opening it feeds the fire with air. Then leave the space closed and cool it from outside."),
 ("The four elements of fire prevention on a yacht",
  "Control the fuel (gas, diesel, petrol, spirits, oily rags),<br>control ignition (galley, electrics, smoking, engine),<br>keep the boat clean and dry in the bilge and engine bay,<br>and check installations — gas hoses, jubilee clips, wiring, exhaust lagging — before the season and on passage."),
 ("Why is LPG particularly dangerous on a boat, and how is the risk managed?",
  "Butane and propane are heavier than air, so a leak sinks into the bilge and forms an explosive pocket that will not ventilate out. Manage it with the bottle in a self-draining locker vented overboard,<br>a shut-off at the bottle and at the cooker,<br>an in-date flexible hose,<br>a bubble tester or leak detector,<br>and a habit of turning gas off at the bottle when not cooking."),
 ("What goes in a grab bag?",
  "Handheld VHF,<br>EPIRB or PLB,<br>handheld GNSS,<br>flares,<br>torch,<br>whistle,<br>water,<br>high-energy food,<br>first aid and seasickness tablets,<br>thermal protective aids,<br>sun protection,<br>a knife,<br>a hand bailer,<br>spare glasses and any essential medication,<br>plus passports and ship's papers if there is time."),
 ("When do you actually get into the liferaft?",
  "Only when you are certain you must step <b>up</b> into it — the yacht is your best liferaft until she is definitely sinking or on fire beyond control. Send a distress alert first, put on lifejackets, take the grab bag, and never cut the painter until everyone is aboard."),
 ("How do you launch and board a liferaft?",
  "Secure the painter to a strong point on the boat,<br>throw the raft over the leeward side,<br>pull the painter hard to fire the gas bottle,<br>board dry from the deck if you can,<br>get everyone in,<br>then stream the drogue,<br>close the canopy,<br>cut the painter and bail out. Take seasickness tablets early."),
 ("What is a radar reflector for and why does it matter in fog?",
  "It makes a small glassfibre yacht visible on a ship's radar. Mount it as high as possible and the right way up. It is not a guarantee — a yacht is a poor radar target, and in poor visibility you should assume you have not been seen."),
 ("EPIRB versus PLB versus SART versus AIS beacon",
  "<b>EPIRB</b> — 406 MHz beacon registered to the vessel, alerts search and rescue via satellite worldwide.<br><b>PLB</b> — the same idea, registered to a person and carried on them.<br><b>SART</b> — radar transponder that paints a line of blips on a searching ship's radar.<br><b>AIS beacon</b> — alerts nearby AIS-equipped vessels, ideal for a man overboard."),
 ("What lifesaving gear should you check before every passage?",
  "Lifejackets fitted and serviced,<br>harnesses and tethers,<br>jackstays,<br>lifebuoy and danbuoy free to release,<br>liferaft in date and lashed with a hydrostatic release or slip,<br>flares in date,<br>extinguishers charged,<br>first aid kit stocked,<br>bilge pumps working,<br>torch batteries good,<br>and softwood bungs to hand."),
 ("How do you deal with a crew member who is seriously seasick?",
  "Take it seriously: it causes dehydration, poor judgement and accidents. Get them on deck in the fresh air,<br>low down and warm,<br>looking at the horizon,<br>with something in their stomach and a job to do such as steering. Clip them on,<br>keep fluids going,<br>and treat them as a casualty, not a nuisance. Tablets work best taken well before you sail."),
 ("Cold water shock — what happens and what do you do?",
  "Sudden immersion causes an involuntary gasp, hyperventilation, a spike in heart rate and loss of grip and swimming ability within a couple of minutes. <b>In the water: float to live</b> — fight the instinct to thrash, lean back with your head back and airway clear, sculling gently, for 60 to 90 seconds until the gasping passes; then shout for help or swim.<br><b>As rescuer:</b> get them out fast, keep them <b>horizontal</b>, insulate them, no alcohol, no rubbing the limbs, handle them gently to avoid post-immersion collapse, and get medical help."),
 ("Hypothermia — the signs and the treatment",
  "Shivering,<br>then pale cold skin,<br>slurred speech,<br>clumsiness,<br>confusion,<br>apathy and finally collapse. Handle very gently,<br>get them into shelter,<br>remove wet clothing,<br>insulate the whole body including the head,<br>warm drinks only if fully conscious,<br>no alcohol,<br>no rubbing,<br>no hot bath,<br>and call for medical help early."),
 ("What is a jackstay and how should a tether be used?",
  "A jackstay is a webbing or wire line running fore and aft along the deck. Clip the harness tether to it so you can move without unclipping. Keep the tether short enough that you cannot go over the side, and clip on inside the cockpit before you go out on deck.", "fig:deck-fittings@jackstay"),
 ("Minimum first aid you should be able to do at sea",
  "Assess response, airway, breathing and circulation;<br>control severe bleeding with direct pressure;<br>treat shock, burns, hypothermia and near-drowning;<br>recognise when to call for medical advice by VHF (a PAN-PAN to the Coastguard) and how to describe symptoms clearly."),
 ("Are flares a legal requirement, and what are the modern alternatives?",
  "Pyrotechnic flares are <b>not</b> legally required for UK pleasure vessels under 13.7 m; they are compulsory for vessels of 13.7 m and over. Many cruisers now rely on a VHF/DSC set with a correctly registered MMSI,<br>an EPIRB or PLB,<br>an AIS beacon on each lifejacket,<br>a mobile phone,<br>and an electronic visual distress signal. If you do carry flares, everyone aboard must know where they are and how to fire them — and you own the disposal problem."),
 ("What is a hydrostatic release unit and why does the liferaft need one?",
  "A link that holds the liferaft in its cradle but releases automatically at about 4 m of water depth, so the raft frees itself if the yacht sinks before anyone can launch it. Lash the raft with the HRU rather than with rope,<br>check its expiry date,<br>and make sure the painter is made fast to a strong point on the <b>boat</b>, not to the cradle."),
]),

("colregs", "05 IRPCS — rules of the road", [
 ("What does IRPCS stand for, and do they apply to a small yacht?",
  "The International Regulations for Preventing Collisions at Sea 1972, as amended — the COLREGs. They apply to <b>all</b> vessels on the high seas and connected navigable waters, whatever their size. There is no small-boat exemption from the steering and sailing rules."),
 ("Rule 2 — the responsibility rule",
  "Nothing in the rules excuses any vessel from the consequences of neglecting them or of neglecting the ordinary practice of seamen. And where a special circumstance or immediate danger makes it necessary, you must depart from the rules to avoid collision. Good seamanship overrides everything."),
 ("Rule 5 — look-out",
  "Every vessel shall at all times maintain a proper look-out by sight and hearing, and by all available means appropriate to the prevailing circumstances, so as to make a full appraisal of the situation and the risk of collision."),
 ("Rule 6 — safe speed. What determines it?",
  "You must always proceed at a speed at which you can take proper and effective action to avoid collision and stop within an appropriate distance. Factors: visibility,<br>traffic density,<br>your manoeuvrability,<br>background lights at night,<br>sea and wind state,<br>draught in relation to depth,<br>and the characteristics and limitations of your radar."),
 ("Rule 7 — how do you know there is a risk of collision?",
  "Use all available means. If the compass bearing of an approaching vessel does not appreciably change, risk of collision exists — and it can exist even with an appreciable bearing change when closing a very large vessel or a tow, or at close range. Assume risk exists if you are in any doubt, and do not rely on scanty information, especially scanty radar information."),
 ("Rule 8 — what must action to avoid collision be like?",
  "<b>Positive</b>,<br>made in <b>ample time</b>,<br>and with <b>due regard to good seamanship</b>. Any alteration should be large enough to be readily apparent visually or by radar; a succession of small alterations should be avoided. Prefer a course alteration if there is room. Slacken speed, stop or reverse if necessary. The action must result in passing at a safe distance, checked until finally past and clear."),
 ("Rule 9 — narrow channels",
  "Keep as near to the outer limit of the channel on your <b>starboard</b> side as is safe and practicable. A vessel under 20 m, or a sailing vessel, must not impede a vessel that can safely navigate only within the channel. Do not cross a channel if that impedes such a vessel. Avoid anchoring in a narrow channel."),
 ("Rule 10: how do you use a traffic separation scheme, and what applies if you have to cross one?",
  "Proceed in the appropriate lane in the general direction of flow, and join or leave at the termination or at as small an angle to the flow as practicable. <b>Avoid crossing lanes</b> so far as practicable; if you must cross, cross on a <b>heading as nearly as practicable at right angles</b> to the flow — a heading, so you do not offset for tide. A vessel under 20 m or a sailing vessel must not impede a power-driven vessel following a lane. Vessels under 20 m, sailing vessels and vessels fishing <b>may</b> use the inshore traffic zone."),
 ("Rule 12 — two sailing vessels approaching",
  "<b>Different tacks</b>: the vessel on <b>port tack</b> keeps out of the way. <b>Same tack</b>: the <b>windward</b> vessel keeps out of the way. If you are on port tack and cannot tell which tack a vessel to windward is on, keep out of her way.", "ds-colregs-sail.png"),
 ("Which side is the windward side for the purposes of Rule 12?",
  "The side <b>opposite</b> to that on which the mainsail is carried — so the opposite side to the boom. On a square-rigged vessel it is the side opposite the largest fore-and-aft sail."),
 ("Rule 13 — overtaking",
  "The <b>overtaking</b> vessel keeps out of the way, and remains responsible until she is <b>finally past and clear</b>. A vessel is overtaking when she comes up from more than 22.5&deg; abaft the other's beam. A subsequent change of bearing does not turn it into a crossing situation, and if in doubt assume you are overtaking. Rule 13 applies <b>notwithstanding</b> Rules 4 to 18, so it overrides the Rule 18 hierarchy: a sailing vessel overtaking a power-driven vessel must keep out of the way.", "ds-colregs-power.png"),
 ("Rule 14 — head-on situation",
  "Two <b>power-driven</b> vessels meeting on reciprocal or nearly reciprocal courses so as to involve risk of collision: <b>each</b> alters course to <b>starboard</b> so they pass <b>port to port</b>. If in doubt whether it is a head-on situation, assume it is and act accordingly.", "ds-colregs-power.png"),
 ("Rule 15 — crossing situation",
  "When two power-driven vessels are crossing, the vessel which has the other on her own <b>starboard</b> side keeps out of the way and shall, if the circumstances admit, avoid crossing ahead of the other.", "ds-colregs-power.png"),
 ("Rule 16 — the give-way vessel's duty",
  "Take early and substantial action to keep well clear."),
 ("Rule 17 — the stand-on vessel's duty",
  "Keep your course and speed. But as soon as it becomes apparent that the give-way vessel is not taking appropriate action, you may take action; and when collision cannot be avoided by the give-way vessel's action alone, you <b>must</b> take the best avoiding action. In a crossing situation, a power-driven stand-on vessel should <b>not</b> alter to port for a vessel on her own port side."),
 ("Rule 18 — the order of responsibilities between vessels",
  "<b>Except where Rules 9, 10 and 13 otherwise require</b> — so the hierarchy is suspended in a narrow channel, in a traffic separation scheme, and when overtaking. In order, each keeping out of the way of those above: not under command;<br>restricted in ability to manoeuvre;<br>constrained by draught (international rules only, and only to be 'not impeded');<br>engaged in fishing;<br>sailing;<br>power-driven;<br>seaplanes and WIG craft.", "ds-colregs-sail.png"),
 ("A yacht under sail with the engine running in gear meets a motor cruiser — who gives way?",
  "Neither has priority as a sailing vessel: under Rule 3 a vessel under sail with her propelling machinery in use is a <b>power-driven vessel</b>. Rule 12 does not apply. Settle it on geometry under the power-driven rules — Rule 14 if head-on, so both alter to starboard;<br>Rule 15 if crossing, so the one with the other on her own starboard side gives way;<br>Rule 13 if overtaking."),
 ("What day shape should a sailing vessel motor-sailing show?",
  "A black <b>cone, point down</b>, forward where it can best be seen."),
 ("Rule 19: who does it apply to, and what four things does it require of you?",
  "It applies when vessels are not in sight of one another in or near an area of restricted visibility, and to <b>all</b> vessels — there is no stand-on vessel. Proceed at a safe speed adapted to the visibility; a <b>power-driven</b> vessel shall have her engines ready for immediate manoeuvre. Sound the Rule 35 fog signals. If you detect another vessel <b>by radar alone</b>, determine early whether a close-quarters situation is developing or risk of collision exists, and if so take avoiding action in ample time.", "ds-colregs-sail.png"),
 ("Rule 19 — which alterations should you avoid?",
  "When taking avoiding action against a vessel detected <b>by radar alone</b> (Rule 19(d)): so far as possible avoid an alteration of course <b>to port</b> for a vessel forward of the beam, other than one being overtaken, and avoid an alteration <b>towards</b> a vessel abeam or abaft the beam. Both are sound practice in fog generally."),
 ("Rule 19 — what must you do if you hear a fog signal forward of your beam?",
  "Unless it is determined that no risk of collision exists, reduce speed to the minimum at which you can be kept on course, and if necessary <b>take all way off</b> and in any event navigate with extreme caution until the danger of collision is over."),
 ("Rule 20 — when must lights be shown?",
  "From sunset to sunrise; also from sunrise to sunset in restricted visibility; and they may be exhibited at any other time when deemed necessary. <b>From sunset to sunrise</b> no other lights may be exhibited that could be mistaken for the prescribed lights, impair their visibility or distinctive character, or interfere with keeping a proper look-out. Shapes are shown by day."),
 ("Rule 3 — what is a 'vessel not under command'?",
  "A vessel that through some exceptional circumstance is unable to manoeuvre as required by the rules and so cannot keep out of the way — for example steering failure or a total engine breakdown."),
 ("Rule 3 — what is a 'vessel restricted in her ability to manoeuvre'?",
  "A vessel that from the nature of her work is restricted in her ability to manoeuvre as required and so cannot keep out of the way. Deemed to include: laying, servicing or picking up a navigation mark, submarine cable or pipeline;<br>dredging, surveying or underwater operations;<br>replenishment or transfer of persons, stores or cargo while underway;<br>launching or recovering aircraft;<br>mine clearance;<br>and towing where the tow severely restricts the towing vessel and her tow in their ability to deviate."),
 ("Rule 3 — what is a 'vessel engaged in fishing'?",
  "A vessel fishing with nets, lines, trawls or other apparatus that <b>restricts her manoeuvrability</b>. It does <b>not</b> include a vessel fishing with trolling lines, so a boat with rods has no special status."),
 ("Rule 3 — what is meant by 'restricted visibility'?",
  "Any condition in which visibility is restricted by fog, mist, falling snow, heavy rainstorms, sandstorms or any similar cause."),
 ("Rule 3 — 'underway' versus 'making way'",
  "<b>Underway</b> means not at anchor, not made fast to the shore and not aground — you can be underway and drifting with no way on. <b>Making way</b> means moving through the water. The distinction changes both your lights and your fog signal."),
 ("A large ship is approaching in a narrow buoyed channel and you are under sail in a 10 m yacht. What do you do?",
  "Get out of her way early — Rule 9 says a vessel under 20 m or a sailing vessel must not impede a vessel that can only navigate safely inside the channel. Move outside the channel if the depth allows, or keep to its starboard edge, well clear. Do not stand on your 'rights': you have none here."),
 ("What does five or more short and rapid blasts mean, and what should you do on hearing them?",
  "'I do not understand your intentions' or 'I doubt whether you are taking sufficient action to avoid collision' (Rule 34(d)), given by vessels in sight of one another and optionally supplemented by at least five short rapid flashes. Assume it is aimed at you. Take the way off or slow right down while you work out the geometry, then act decisively: if you are the give-way vessel, a large alteration to <b>starboard</b> and a substantial reduction in speed. Never alter to port for a vessel on your own port side."),
 ("You are the stand-on vessel and the other vessel is doing nothing. What is your legal position?",
  "Rule 17 lets you act as soon as it becomes apparent she is not taking appropriate action, and <b>requires</b> you to take the best avoiding action once collision cannot be avoided by her action alone. Standing on to the point of collision is a breach of the rules, not a defence."),
 ("Two power-driven vessels crossing: A has B on her port bow. What must A do?",
  "A is the <b>stand-on</b> vessel — B has A on her own starboard side, so B gives way. A holds course and speed, watches carefully, and acts under Rule 17 if B does not."),
 ("What is the difference between the international rules and local harbour rules?",
  "Local authorities may make byelaws and directions — speed limits,<br>prohibited areas,<br>small-craft channels,<br>precautionary areas,<br>moving-prohibited zones around large ships. They supplement the IRPCS. Check the almanac and harbour guide before you arrive, and comply with both."),
 ("What does 'shall not impede' actually oblige you to do?",
  "Rule 8(f). Take <b>early</b> action to leave enough sea room for the other vessel's safe passage — you must keep out of her way <b>before</b> a close-quarters situation exists. It does not give her right of way: once you are approaching so as to involve risk of collision, both of you are still bound by the ordinary steering and sailing rules, and neither is relieved of them."),
 ("Rule 11 — when do Rules 12 to 18 apply at all?",
  "Only when vessels are <b>in sight of one another</b>. If you cannot see her — in fog, or on radar or AIS only — Rules 12 to 18 do not apply and there is no give-way or stand-on vessel: you are in <b>Rule 19</b>, and so is she.", "ds-colregs-sail.png"),
 ("You are under sail, overtaking a motor cruiser. Who keeps clear?",
  "<b>You do.</b> Rule 13 applies notwithstanding Rules 4 to 18, so it overrides the Rule 18 hierarchy: the overtaking vessel keeps out of the way, whatever she is, until she is <b>finally past and clear</b>. Sail beats power in a crossing situation, never in an overtaking one.", "ds-colregs-power.png"),
]),

("lights", "06 Lights and shapes", [
 ("Define masthead light, sidelights, sternlight and all-round light with their arcs.",
  "<b>Masthead light</b> — white, 225&deg;, from ahead to 22.5&deg; abaft the beam on each side, on the fore-and-aft centreline.<br><b>Sidelights</b> — green to starboard and red to port, each 112.5&deg;, from ahead to 22.5&deg; abaft the beam.<br><b>Sternlight</b> — white, 135&deg;, 67.5&deg; each side of right aft.<br><b>All-round light</b> — 360&deg;. In a vessel under 20 m the sidelights may be combined in <b>one lantern on the centreline</b>. A <b>towing light</b> is yellow with the sternlight's 135&deg; characteristics, and a <b>flashing light</b> flashes 120 times a minute or more.", "ds-light-arcs.png"),
 ("What lights does a power-driven vessel under 50 m show when underway?",
  "A masthead light, sidelights and a sternlight. Under 12 m she may instead show an <b>all-round white light and sidelights</b>. Under 7 m, and not exceeding 7 knots, she may show an <b>all-round white light alone</b>, with sidelights only if practicable.", "ds-lights-recognition.png"),
 ("What extra light does a power-driven vessel of 50 m or more show?",
  "A <b>second masthead light abaft of and higher than</b> the forward one. Seeing two white masthead lights in a vertical line tells you it is a big ship, and their relative position gives you her aspect.", "ds-lights-recognition.png"),
 ("What lights does a sailing vessel under sail show?",
  "Sidelights and a sternlight — and <b>no masthead light</b>. Under 20 m these may be combined in a single tricolour lantern at or near the top of the mast. She may instead add an optional all-round <b>red over green</b> at or near the top of the mast — but <b>never together with the tricolour</b> (Rule 25(c)).", "ds-lights-recognition.png"),
 ("Why must you not use a masthead tricolour and deck-level sidelights at the same time?",
  "Because you would then show two sets of sidelights, which is not a recognised light pattern and confuses another vessel about your size and aspect. Use one or the other."),
 ("What lights may a sailing vessel under 7 m, or a vessel under oars, show?",
  "A sailing vessel under 7 m shows the normal lights, or a tricolour, <b>if practicable</b>; if she does not, she must have ready at hand an <b>electric torch or lighted lantern showing a white light</b> to exhibit in sufficient time to prevent collision. A vessel under oars has the same torch option at <b>any</b> length (Rule 25(d))."),
 ("What lights does a vessel at anchor show?",
  "An all-round white light forward where it can best be seen; a vessel of 50 m or more shows a second one aft and lower. Any vessel at anchor <b>may</b>, and one of <b>100 m or more shall</b>, use her working lights to illuminate her decks. By day, one <b>black ball</b>. A vessel under 7 m is exempt unless anchored in or near a narrow channel, fairway, anchorage or where other vessels normally navigate.", "ds-lights-recognition.png"),
 ("What lights and shapes does a vessel aground show?",
  "The anchor light(s) plus <b>two all-round red lights</b> in a vertical line. By day, <b>three black balls</b> in a vertical line. A vessel under 12 m aground is not required to show these (Rule 30(f)) — she still shows her anchor light."),
 ("What lights and shapes does a vessel not under command show?",
  "<b>Two all-round red lights</b> in a vertical line, plus sidelights and sternlight if making way. By day, <b>two black balls</b>. A vessel under 12 m is not required to show these (Rule 27(g)), but doing so, or attracting attention under Rule 36, is still the seamanlike thing. Mnemonic: 'red over red, the captain is dead'.", "ds-lights-recognition.png"),
 ("What lights and shapes does a vessel restricted in her ability to manoeuvre show?",
  "<b>Red, white, red</b> all-round lights in a vertical line, plus normal steaming lights if making way. By day, <b>ball, diamond, ball</b> in a vertical line. A vessel under 12 m is not required to show these, except when engaged in diving operations (Rule 27(g)).", "ds-lights-recognition.png"),
 ("What lights and shape does a vessel constrained by her draught show?",
  "She <b>may</b> show, in addition to her normal power-driven lights, <b>three all-round red lights</b> in a vertical line; by day, a black <b>cylinder</b>. Because it is optional, a deep-draught ship in a dredged channel may show nothing special — judge by the channel, not by the lights.", "ds-lights-recognition.png"),
 ("What lights and shape does a trawler show?",
  "<b>Green over white</b> all-round lights, plus sidelights and sternlight when making way. By day, two cones apexes together in a vertical line; under 20 m she may show a <b>basket</b> instead. A trawler of 50 m or more also shows a masthead light abaft of and higher than the green. Mnemonic: 'green over white, trawling tonight'.", "ds-lights-recognition.png"),
 ("What lights does a vessel fishing other than trawling show?",
  "<b>Red over white</b> all-round lights, plus sidelights and sternlight when making way. If the gear extends more than 150 m horizontally, an all-round white light — or by day a cone <b>apex upwards</b> — in the direction of the gear. By day, two cones apexes together, or a <b>basket</b> if under 20 m. Mnemonic: 'red over white, fishing at night'.", "ds-lights-recognition.png"),
 ("What lights does a vessel towing show, and what changes once the tow exceeds 200 m?",
  "<b>Two masthead lights</b> in a vertical line,<br>sidelights,<br>sternlight,<br>and a <b>yellow towing light</b> above the sternlight. If the tow exceeds 200 m she shows three masthead lights in a vertical line and, by day, a black <b>diamond</b> on both towing and towed vessel.", "ds-lights-recognition.png"),
 ("What lights does a pilot vessel on duty show?",
  "<b>White over red</b> all-round lights at or near the masthead, plus sidelights and sternlight when underway, or anchor lights when at anchor. Mnemonic: 'white over red, pilot ahead'.", "ds-lights-recognition.png"),
 ("What lights and shape does a vessel engaged in dredging or underwater operations show?",
  "The restricted-in-ability-to-manoeuvre lights (<b>red, white, red</b>) or shapes (<b>ball, diamond, ball</b>), plus masthead light, sidelights and sternlight when making way; and where an obstruction exists, <b>two all-round red lights or two balls</b> on the obstructed side and <b>two all-round green lights or two diamonds</b> on the side it is safe to pass. At anchor she shows these <b>instead of</b> the Rule 30 anchor lights — so pass on the green side."),
 ("What lights does a vessel engaged in minesweeping show?",
  "In addition to her power-driven lights, or her anchor lights if at anchor, <b>three all-round green lights or three balls</b> — one near the foremast head and one at each end of the fore yard. They mean it is dangerous to approach within <b>1,000 m</b>."),
 ("What lights does a hovercraft in non-displacement mode show?",
  "Her normal power-driven vessel lights plus an all-round <b>flashing yellow</b> light."),
 ("You see a red light and a green light and a white light above and between them, all steady. What is it and what do you do?",
  "A power-driven vessel of under 50 m, coming towards you more or less head-on. You are seeing both sidelights so she is roughly bow-on. If you are also power-driven this is a Rule 14 head-on situation — both alter to starboard. Keep watching the bearing."),
 ("You see only a green light and a white masthead light. What are you looking at?",
  "The starboard side of a power-driven vessel crossing from your left to your right. She is on your port side, so if you are power-driven you are the stand-on vessel — but keep checking the bearing."),
 ("You see only a red light and a white masthead light. What are you looking at, and what must you do?",
  "The port side of a power-driven vessel crossing from your right to your left. She is on <b>your starboard side</b>, so if you are power-driven you must <b>give way</b>: alter to starboard and pass astern of her."),
 ("You see a single white light and nothing else. Name four things it could be.",
  "The sternlight of a vessel you are overtaking;<br>the anchor light of a vessel at anchor;<br>the all-round white light of a small power-driven vessel under 12 m seen from astern;<br>a vessel under 7 m showing a torch;<br>one of the two masthead lights of a big ship at extreme range;<br>or the all-round white light of a power-driven vessel under 7 m doing 7 knots or less, which may legally show <b>no sidelights at all</b> and looks the same from every direction. Treat it with suspicion and take a bearing."),
 ("You see two white lights in a vertical line, the higher one to the right of the lower. What is it doing?",
  "The higher of two masthead lights is the <b>after</b> one, so her stern is to the right and her bow to the left: a power-driven vessel of 50 m or more crossing right to left. Confirm with the sidelight. <b>If you can see no sidelight at all, suspect a large vessel at anchor</b> — her anchor lights are also two whites at different heights, but the <b>forward</b> one is higher, and she is not moving."),
 ("Sector lights — what are they for?",
  "A light that shows different colours over different arcs, so its colour tells you which sector you are in. Typically <b>white</b> over the safe approach and <b>red</b> and <b>green</b> over the dangerous sides. Charted as, for example, Oc WRG 10s, with the sector bearings given <b>from seaward towards the light</b>."),
 ("Leading lights",
  "Two lights, a front and a rear, at different heights. Keep them vertically in line and you are on the leading line into the harbour. The chart gives the leading line's bearing."),
 ("A directional light",
  "Shows a narrow white beam along the safe approach with red and green either side, giving a precise line to steer without a second mark."),
 ("What is the difference between the range of a light and its visibility to you?",
  "The charted range is usually the <b>nominal range</b> in clear weather at a stated luminosity, or the <b>luminous range</b>. What you actually see is also limited by the <b>geographical range</b>, which depends on the height of the light and your own height of eye and so on the curvature of the earth. In poor visibility you may see much less than either."),
 ("What is 'loom' and 'rising' or 'dipping' a light?",
  "The <b>loom</b> is the glow of a light seen before the light itself, reflected off haze. <b>Raising</b> or <b>dipping</b> a light is the moment it appears or disappears over the horizon; with the light's height and your height of eye you can turn that into a distance off, which gives a position line."),
 ("How far must navigation lights be visible, by vessel length?",
  "Minimum ranges under Rule 22. <b>50 m or more</b>: masthead 6 M; sidelights, sternlight, towing and all-round lights 3 M. <b>12 m up to 50 m</b>: masthead 5 M, or 3 M if under 20 m; all others 2 M. <b>Under 12 m</b>: masthead 2 M, sidelights 1 M, sternlight, towing and all-round 2 M. Your sidelights may be visible only a mile — assume a ship has not seen you."),
 ("What lights must a yacht show at night when motor-sailing?",
  "The lights of a <b>power-driven vessel</b>: masthead (steaming) light, sidelights and sternlight. You <b>cannot</b> use a masthead tricolour, because there is no masthead light in it and steaming light plus tricolour is not a recognised pattern — switch to deck-level sidelights and sternlight and put the steaming light on. By day, the black cone point down.", "ds-lights-recognition.png"),
 ("What does a small vessel engaged in diving operations show?",
  "Where she is too small to show the full dredging signals: <b>red, white, red</b> all-round lights in a vertical line, and a <b>rigid replica of code flag A</b> not less than 1 m high, visible all round (Rule 27(e)). Divers are in the water, so pass wide and slow. The under-12 m exemption in Rule 27(g) does <b>not</b> apply to diving."),
 ("Which lights and shapes is a small vessel excused from showing?",
  "<b>Under 12 m</b> — need not show the NUC or RAM lights of Rule 27, except when diving; need not show the aground lights or shapes; need not carry a whistle or bell.<br><b>Under 7 m</b> — at anchor, no light or ball needed unless in or near a narrow channel, fairway, anchorage or where other vessels normally navigate; under sail, a torch or lantern in lieu if the normal lights are impracticable. Being excused is not the same as being invisible: show something."),
]),

("sound", "07 Sound signals", [
 ("Define a short blast and a prolonged blast.",
  "A <b>short blast</b> is about 1 second. A <b>prolonged blast</b> is 4 to 6 seconds.", "ds-sound-signals.png"),
 ("What do one, two and three short blasts mean?",
  "Given by a <b>power-driven vessel underway</b>, when <b>in sight</b> of another vessel and actually manoeuvring: <b>one</b> — 'I am altering my course to starboard';<br><b>two</b> — 'I am altering my course to port';<br><b>three</b> — 'I am operating astern propulsion'. They are statements of what you <b>are doing</b>, not requests — and they are not fog signals.", "ds-sound-signals.png"),
 ("What do five or more short and rapid blasts mean?",
  "'I do not understand your intentions' or 'I doubt whether you are taking sufficient action to avoid collision' (Rule 34(d)). It is the wake-up signal.", "ds-sound-signals.png"),
 ("In a narrow channel, what signal means 'I intend to overtake you on your starboard side'?",
  "Two prolonged blasts followed by one short blast. For the port side: two prolonged followed by two short. The vessel to be overtaken agrees with one prolonged, one short, one prolonged, one short.", "ds-sound-signals.png"),
 ("What signal do you sound when approaching a bend where other vessels may be hidden?",
  "One <b>prolonged</b> blast (Rule 34(e)). Any vessel within earshot round the bend answers with one prolonged blast.", "ds-sound-signals.png"),
 ("Fog signal — power-driven vessel making way through the water",
  "One <b>prolonged</b> blast at intervals of not more than 2 minutes.", "ds-sound-signals.png"),
 ("Fog signal — power-driven vessel underway but stopped and making no way",
  "<b>Two prolonged</b> blasts in succession, about 2 seconds apart, at intervals of not more than 2 minutes.", "ds-sound-signals.png"),
 ("Fog signal — sailing vessel underway",
  "One prolonged followed by <b>two short</b> blasts, at intervals of not more than 2 minutes. The same signal is used by a vessel not under command,<br>restricted in her ability to manoeuvre,<br>constrained by draught,<br>fishing,<br>or towing or pushing.", "ds-sound-signals.png"),
 ("Fog signal — vessel at anchor",
  "Rapid ringing of the bell for about 5 seconds at intervals of not more than one minute. In a vessel of <b>100 m or more</b>, the bell forward and, immediately after, the gong sounded rapidly for about 5 seconds aft. She may also sound one short, one prolonged and one short blast to warn an approaching vessel of her position.", "ds-sound-signals.png"),
 ("Fog signal — vessel aground",
  "Three separate and distinct strokes on the bell, then the rapid ringing, then three more strokes, at intervals of not more than one minute — plus, if appropriate, a whistle signal.", "ds-sound-signals.png"),
 ("Fog signal — vessel being towed",
  "The vessel towed, or the last vessel of the tow if manned, sounds one prolonged followed by <b>three short</b> blasts at intervals of not more than 2 minutes, and where practicable immediately after the towing vessel's signal."),
 ("What are the sound signalling requirements for a vessel of less than 12 m?",
  "She is not obliged to carry the prescribed bell or whistle, but she <b>must</b> carry some other means of making an efficient sound signal, and must use it at intervals of not more than 2 minutes.", "ds-sound-signals.png"),
 ("Fog signal — pilot vessel on duty",
  "In addition to her other signals she may sound an identity signal of <b>four short blasts</b>.", "ds-sound-signals.png"),
 ("Rule 36 — what may you do to attract attention?",
  "Make any light or sound signal that cannot be mistaken for one of the prescribed signals, or direct a searchlight beam towards the danger, in a way that does not embarrass any other vessel. A high-intensity intermittent or revolving light such as a strobe is not to be used."),
 ("What sound signal accompanies a distress situation?",
  "Continuous sounding of any fog-signalling apparatus is a recognised distress signal (Annex IV). So is a gun or other explosive signal fired at intervals of about a minute."),
 ("What sound signalling equipment must a vessel carry?",
  "Rule 33. <b>12 m or more</b> — a whistle <b>and</b> a bell.<br><b>100 m or more</b> — a gong in addition, of a tone that cannot be confused with the bell.<br><b>Under 12 m</b> — none of these is required, but she must have some other means of making an efficient sound signal, used at intervals of not more than 2 minutes in fog.", "ds-sound-signals.png"),
 ("May manoeuvring signals be made with a light?",
  "Yes (Rule 34(b)). Any vessel may supplement the whistle signals with an all-round white light: <b>one flash</b> altering to starboard,<br><b>two</b> to port,<br><b>three</b> operating astern propulsion, repeated while the manoeuvre is carried out. Each flash about a second, about a second between flashes, at least 10 seconds between successive signals."),
]),
]
