# -*- coding: utf-8 -*-
"""RYA Day Skipper cards, part B: navigation, chartwork, tides, buoyage, meteorology."""

SECTIONS_B = [
("position", "08 Position, distance and speed", [
 ("How is latitude defined and measured?",
  "The angular distance north or south of the equator, from 0&deg; at the equator to 90&deg; at the poles, measured up the <b>side</b> of the chart. Parallels of latitude are all parallel to the equator.", "fig:latlong@latitude"),
 ("How is longitude defined and measured?",
  "The angular distance east or west of the Greenwich meridian, from 0&deg; to 180&deg;, measured along the <b>top and bottom</b> of the chart. Meridians of longitude all run from pole to pole and converge at the poles.", "fig:latlong@longitude"),
 ("How do you write a position, and in what order?",
  "Latitude first, then longitude, each in degrees, minutes and decimals of a minute, with the hemisphere letter: <b>50&deg;42'.3 N 001&deg;18'.7 W</b>. Longitude is written with three digits of degrees.", "fig:latlong@position"),
 ("What is a nautical mile, and how does it relate to latitude?",
  "One minute of latitude, defined internationally as <b>1,852 metres</b>. Because meridians converge, one minute of <b>longitude</b> equals a nautical mile only at the equator — so always measure distance on the <b>latitude</b> scale at the side of the chart.", "fig:latlong@mile,latitude"),
 ("What is a knot?",
  "One nautical mile per hour."),
 ("The three quantities in every speed, time and distance sum",
  "Distance = speed &times; time.<br>Speed = distance / time.<br>Time = distance / speed. Work in decimal hours, or use 'minutes = distance &times; 60 / speed'."),
 ("At 5.5 knots, how long does 8.3 miles take?",
  "8.3 / 5.5 = 1.509 hours. 0.509 &times; 60 = 30.5, so <b>1 h 30&frac12; min</b> — call it 1 h 31 for an ETA. (Or 8.3 &times; 60 / 5.5 = 90.5 minutes.)"),
 ("What is a great circle and a rhumb line?",
  "A <b>great circle</b> is the shortest route between two points on the globe. A <b>rhumb line</b> crosses every meridian at the same angle and plots as a straight line on a Mercator chart — it is what you steer on a short coastal passage, where the difference is negligible."),
 ("Why is a Mercator projection convenient for navigation, and what is its cost?",
  "Meridians and parallels are straight and at right angles, so a constant course is a straight line and angles are true. The cost is that scale increases with latitude, so areas at high latitude are exaggerated and you must measure distance at the latitude you are in."),
 ("What is a true bearing, and how is it written?",
  "A direction measured clockwise from true north, always in three figures: 007&deg;, 095&deg;, 270&deg;. Suffix T for true, M for magnetic, C for compass."),
 ("Relative bearing versus compass bearing",
  "A <b>relative</b> bearing is measured from the boat's head — 'a ship on the starboard bow', 'fine to port', '30&deg; on the port bow'. A <b>compass</b> bearing is measured from north. Convert by adding a relative bearing measured <b>clockwise from the bow</b> to your heading, subtracting 360&deg; if the total exceeds it. If it is given as so many degrees <b>on the port bow</b>, subtract instead: heading 100&deg;, 30&deg; on the port bow = 070&deg;."),
 ("Speed over the ground versus speed through the water",
  "<b>Through the water</b> is what the log reads. <b>Over the ground</b> is what the GNSS reads, and it includes the tidal stream. The difference is the tide, plus any log error."),
 ("Course, heading and track — what is the difference?",
  "<b>Heading</b> is where the bow points at this instant. <b>Course</b> is the direction you intend to steer. <b>Water track</b> is the path through the water, so heading corrected for leeway. <b>Ground track</b> (course over ground) is the path over the seabed, so water track corrected for tide."),
 ("What is the depth reading on an echo sounder measured from, and why does that matter?",
  "It depends on the calibration — from the transducer, from the waterline, or under the keel. Know which yours does and by how much, because your clearance calculation depends on it. Set it to read depth below the keel or add the offset every time."),
 ("What is 'height of eye' used for?",
  "Calculating the distance to the visible horizon and the geographical range of a light, and it appears in the rising/dipping distance tables. In a small yacht it is typically 2-3 m."),
 ("How do you estimate distance off using a vertical sextant angle or by eye?",
  "With the charted height of an object and the measured vertical angle you can read distance off from a table or use distance (M) = 1.854 &times; height (m) / angle (minutes). By eye, learn your own boat's marks: hull down, features visible, windows distinguishable — and always distrust it."),
 ("Why must you check the chart datum of a GNSS position before plotting it?",
  "A latitude and longitude referenced to WGS84 will not fall in the same place on a chart drawn to another horizontal datum such as OSGB36 — the error can be over 100 m. Modern charts note the shift; set the GNSS to match the chart, or apply the correction printed on it."),
]),

("charts", "09 Charts and publications", [
 ("What is the difference between a small-scale and a large-scale chart?",
  "A <b>large-scale</b> chart, such as 1:10,000, covers a small area in great detail — the harbour plan.<br>A <b>small-scale</b> chart, such as 1:150,000, covers a wide area with less detail — the passage chart. Large scale, large detail."),
 ("Which chart should you use for pilotage into a harbour?",
  "The <b>largest scale</b> chart available for that harbour, because it shows the most detail and the least generalisation. Plan the passage on the small-scale chart, do the entrance on the large-scale one."),
 ("What is Admiralty Chart 5011?",
  "The booklet 'Symbols and Abbreviations used on Admiralty Charts'. It is the dictionary for everything printed on a chart, and it is an allowed reference in the shorebased exam."),
 ("Where do you find the chart's units of depth, its scale and its datums?",
  "In the <b>title block</b>, together with the projection,<br>the horizontal (geodetic) datum,<br>the vertical datum for depths and for heights,<br>and the source of the survey. Read it before you use any unfamiliar chart."),
 ("How are depths and drying heights printed on a metric chart?",
  "Depths below chart datum are printed in metres and decimetres up to 20.9 m, e.g. 5&#8323; = 5.3 m, and in whole metres from 21 m down. A <b>drying height</b> above chart datum is printed <u>underlined</u>, e.g. <u>3</u>&#8321; = dries 3.1 m. Heights of land features and lights are in metres above MHWS."),
 ("What do the blue and green tints on a chart mean?",
  "<b>Green</b> marks the area that dries, between chart datum or LAT — the blue/green boundary — and <b>MHWS</b>, the green/buff boundary with the land.<br><b>Blue</b> tints mark shallow water, the darker shade shallowest, bounded by depth contours.<br><b>White</b> is deeper water."),
 ("What is a depth contour and how do you use it in pilotage?",
  "A line joining points of equal charted depth, for example the 5 m or 10 m contour. It is a ready-made safety line: choose a contour that clears the dangers and use the echo sounder to stay outside it — an independent check that needs no visibility."),
 ("What does a Notice to Mariners do, and how do you apply one?",
  "It corrects the chart for changes since printing — moved buoys, new wrecks, changed lights. Apply small corrections in <b>indelible violet ink</b>, and record the notice number and year in the bottom left margin so anyone can see how up to date the chart is."),
 ("Name the main publications a Day Skipper should have aboard.",
  "An almanac (Reeds or the Admiralty equivalent) with tide tables and tidal stream atlases;<br>charts at passage and harbour scale;<br>a pilot book for the area;<br>the Admiralty List of Lights and Fog Signals (NP74&ndash;84) or the almanac's light list;<br>chart 5011;<br>and up-to-date Notices to Mariners."),
 ("What does a nautical almanac contain that you use every trip?",
  "Tide tables for standard ports and differences for secondary ports,<br>tidal curves,<br>tidal stream information,<br>harbour plans and pilotage notes,<br>light and buoy details,<br>radio and Coastguard information,<br>distances,<br>safety and first aid sections,<br>and sunrise, sunset and twilight times."),
 ("What is a tidal stream atlas?",
  "A booklet of chartlets for each hour before and after HW at a standard port, showing the direction and rate of the stream by arrows, with rates given in tenths of a knot for springs and neaps, e.g. 19,34 = 1.9 kn neaps, 3.4 kn springs."),
 ("What are tidal diamonds?",
  "Lettered magenta diamonds on the chart marking positions where tidal stream data is tabulated. The table gives set and rate for each hour relative to HW at the reference port, for springs and for neaps."),
 ("Chart symbols: what are these seabed abbreviations — S, M, Cy, R, Wd, Sh, G, St?",
  "S sand,<br>M mud,<br>Cy clay,<br>R rock,<br>Wd weed,<br>Sh shells,<br>G gravel,<br>St stones. They tell you what your anchor will find."),
 ("How does a chart show a wreck, and what makes one count as dangerous?",
  "A wreck showing part of its hull or masts is drawn in profile. A sunken wreck counts as <b>dangerous</b> — and is enclosed in a dotted danger line — if the least depth over it is 28 m or less, or is unknown; a <b>non-dangerous</b> wreck has the same cross-hatched symbol without the danger line. The least depth is printed over the wreck if known, in a box if it has been wire-swept. Where there is a dotted danger line, the whole enclosed area is the hazard, not just the symbol."),
 ("What is the difference between a rock that is always covered, one that dries, and one that is above water?",
  "A rock <b>awash at chart datum</b> is shown with a specific symbol and no height;<br>a rock that <b>dries</b> carries an underlined drying height;<br>a rock <b>above MHWS</b> is drawn as an islet with a height above MHWS. Always covered rocks show the depth over them."),
 ("What does the compass rose on a chart give you?",
  "The true rose, and inside it the <b>magnetic</b> rose with the variation for a stated year and its annual rate of change — for example '3&deg;15'W 2020 (8'E)'."),
 ("What are electronic charts, and what are the two main kinds?",
  "<b>Raster</b> charts are scanned images of paper charts — everything scales together and detail degrades when you zoom.<br><b>Vector</b> charts (ENCs) are databases of objects, so layers can be turned on and off and objects interrogated, but over-zooming can present a misleadingly detailed picture from a low-detail survey."),
 ("What are the practical limitations of a chart plotter?",
  "Zooming in does not add survey accuracy;<br>the datum may differ from the paper chart;<br>the display shows only a fraction of the chart around you, so you lose the wider picture;<br>it depends on power and on GNSS;<br>and the operator can follow a route across a hazard hidden behind the boat symbol. Keep a paper plot as back-up."),
 ("How often should you record a position, and where?",
  "At regular intervals appropriate to the passage — typically hourly on a coastal passage, and more often in pilotage or near hazards — in the <b>deck log</b>, with time,<br>position,<br>log reading,<br>course steered,<br>weather and any events. If the electronics fail, the log is what lets you start a dead reckoning."),
 ("Why keep a paper plot when the plotter is working perfectly?",
  "Because a total electrical failure, a lightning strike or a GNSS outage leaves you with nothing but the last known position, and because plotting makes you think about the tide, the dangers and the next hour. The <b>deck log</b>, not the plot, is the record of the passage — but the plot is what makes the log usable."),
 ("How do you tell whether the chart in front of you is up to date?",
  "The edition date is in the bottom margin; the Notices to Mariners that have been applied are listed in the bottom <b>left-hand</b> corner in violet ink. Compare that against the current cumulative list of Notices, the almanac's supplement, or the UKHO weekly notices. A leisure chart with no corrections since a five-year-old edition is not a corrected chart."),
]),

("compass", "10 Compass, variation, deviation and leeway", [
 ("What is variation?",
  "The angle between <b>true</b> north and <b>magnetic</b> north at a particular place and date. It is read from the chart's compass rose and changes slowly year on year.", "ds-variation-deviation.png"),
 ("What is deviation?",
  "The error caused by the <b>boat's own</b> magnetic field acting on the compass. It changes with the boat's heading, so it is tabulated on a deviation card, and it can be changed by moving anything magnetic near the compass.", "ds-variation-deviation.png"),
 ("Give the rule for converting between true, magnetic and compass.",
  "<b>Error WEST, compass BEST</b> — a westerly error makes the compass number bigger, so going true to compass you <b>add</b> it.<br><b>Error EAST, compass LEAST</b> — going true to compass you <b>subtract</b> an easterly error. Reverse both when going from compass to true.", "ds-variation-deviation.png"),
 ("Chart course 145&deg;T, variation 3&deg;W, deviation 2&deg;E. What do you steer?",
  "145 + 3 (variation west) = 148&deg;M. 148 &minus; 2 (deviation east) = <b>146&deg;C</b>.", "ds-variation-deviation.png"),
 ("Compass heading 210&deg;C, deviation 4&deg;W, variation 5&deg;W. What is the true heading?",
  "Going compass to true you subtract westerly errors: 210 &minus; 4 = 206&deg;M, 206 &minus; 5 = <b>201&deg;T</b>."),
 ("How do you check the deviation of a steering compass without a swing?",
  "Compare it against a known transit: line up two charted objects, read the compass, and compare with the transit's charted bearing after applying variation. Do it on several headings. Also compare the steering compass with a hand-bearing compass held clear of metal."),
 ("What causes deviation to change unexpectedly?",
  "Anything ferrous or magnetic moved near the compass — a handheld VHF,<br>a mobile phone,<br>a laptop,<br>tinned food,<br>a torch,<br>tools,<br>an outboard,<br>or a loudspeaker. Keep the area around the compass clear and check it if the reading looks odd."),
 ("Where should you stand to take a hand-bearing compass reading?",
  "Somewhere with a clear all-round view and well away from the engine, rigging, winches, electronics and any iron — often the after end of the cockpit or the coachroof. Treat a hand-bearing compass as having no deviation only after you have checked it in that spot."),
 ("What is leeway and how do you allow for it?",
  "The sideways slip of the boat through the water caused by the wind, so the track lies <b>downwind</b> of the heading. Estimate it from your own boat — typically 5-10&deg; hard on the wind, less as you bear away, none dead downwind or motoring in calm water. To make good the track you want, steer <b>upwind</b> of it by the leeway angle.", "ds-variation-deviation.png"),
 ("How can you measure your own leeway?",
  "Look astern at the wake: the angle between the wake and the fore-and-aft line is the leeway. Or compare your compass heading with the ground track from the GNSS after allowing for tide."),
 ("In what order do you apply leeway, variation and deviation?",
  "Work the plot in <b>true</b>. Apply <b>leeway</b> to convert between the water track and the heading, then convert that true heading to magnetic with <b>variation</b>, then to compass with <b>deviation</b>."),
 ("What is a fluxgate compass and what feeds off it?",
  "An electronic compass that senses the earth's field with no moving card. It feeds the autopilot, the instrument repeaters and often the radar and plotter heading display. It still has deviation and needs calibrating by swinging the boat in a circle."),
 ("Why keep a magnetic steering compass when the plotter shows heading?",
  "Because it needs no power. In an electrical failure the magnetic compass, the log, the chart, the almanac and a watch are what get you home."),
 ("Variation is 4&deg;W in 2020 with annual change 8'E. What is it in 2026?",
  "Six years at 8' east per year is 48' east, so 4&deg;00'W &minus; 48' = about <b>3&deg;12'W</b>. In practice round to the nearest degree for chartwork: 3&deg;W."),
 ("Why must a plotted bearing taken with a hand-bearing compass be converted before you draw it?",
  "Because the compass reads magnetic and the chart is drawn true. Apply variation (and any deviation) to get a true bearing, then plot it from the object towards your position."),
]),

("chartwork", "11 Chartwork — fixes, DR, EP and course to steer", [
 ("What is a position line?",
  "A line somewhere on which you know you are: a compass bearing of a charted object, a transit, a depth contour matched to the echo sounder, or a range from a light. Two crossing position lines give a fix; three give a fix and a check."),
 ("What is a fix, how is it marked, and what do you write next to it?",
  "A position established from two or more position lines taken at effectively the same time. Mark it with a <b>dot inside a small circle</b> and label it with the <b>time</b> and the log reading.", "ds-ep-plot.png"),
 ("How do you take a good three-bearing fix?",
  "Choose three charted objects you are certain of, spread roughly 60-120&deg; apart. Take the bearing that is changing <b>slowest</b> first and the fastest-changing one <b>last</b>, note the time and log, convert to true and plot each line from the object.", "ds-fix-pilotage.png"),
 ("What is a cocked hat, and what do you do about it?",
  "The small triangle left when three bearings do not meet at a point. Assume you are at the corner <b>nearest the danger</b>. A large cocked hat means an error — a misidentified mark, a mistake in variation, or too much time between bearings — so take it again.", "ds-fix-pilotage.png"),
 ("What is a dead reckoning position, and how is it marked?",
  "The position worked up from the last fix using only the course steered and the distance run through the water, with <b>no allowance for tide or leeway</b>. Marked with a <b>cross</b> and the time.", "ds-ep-plot.png"),
 ("What is an estimated position, and how is it marked?",
  "The DR position corrected for the tidal stream and for leeway — the best estimate of where you actually are without a fix. Marked with a <b>triangle</b> and the time.", "ds-ep-plot.png"),
 ("How do you construct an estimated position?",
  "From the last fix plot the <b>course steered</b> in true and lay off the distance run by log — that is the <b>DR</b>, marked with a cross.<br>Apply leeway to give the <b>water track</b> (one arrowhead), the same distance run.<br>From the end of the water track plot the <b>tidal stream vector</b> for the time since the fix (three arrowheads).<br>Its end is the <b>EP</b>, marked with a triangle.<br>Fix to EP is the ground track (two arrowheads).", "ds-ep-plot.png"),
 ("What are the arrowhead conventions on a chart plot?",
  "<b>One</b> arrowhead — water track (course through the water).<br><b>Two</b> arrowheads — ground track (course over the ground).<br><b>Three</b> arrowheads — tidal stream vector.", "ds-ep-plot.png"),
 ("How do you work out a course to steer?",
  "Draw the <b>ground track</b> you want from your fix to the destination.<br>From the fix, plot the hour's <b>tide vector</b> (set and drift).<br>Set the dividers to the boat's speed for one hour and, from the end of the tide vector, cut the ground track.<br>The direction of that cut is the <b>water track</b> — your course to steer, before leeway and compass corrections.<br>The tide and boat-speed vectors must cover the <b>same period</b>.", "ds-cts-triangle.png"),
 ("In a course-to-steer triangle, which side is the tide and which is your speed?",
  "The tide vector is plotted <b>from the starting fix</b>, in the direction the stream <b>sets</b>, its length equal to the drift for that period. The boat's speed vector is swung <b>from the end of the tide vector</b> to cut the intended ground track, and must cover the same period as the tide.", "ds-cts-triangle.png"),
 ("How do you find the speed over the ground and the ETA from a course-to-steer triangle?",
  "Measure the ground track from the start to where the boat-speed vector cuts it. If you built the triangle with <b>one hour</b> of tide and one hour of boat speed, that distance in miles is your SOG in knots; for any other period it is the distance made good in that period, so divide by the period to get SOG. Total leg distance divided by SOG gives the time.", "ds-cts-triangle.png"),
 ("What is a running fix and when do you use it?",
  "When you can see only one charted object. Take a bearing,<br>note time and log,<br>run on,<br>take a second bearing,<br>then transfer the first position line forward by the course and distance run (corrected for tide) and cross it with the second. Less accurate than a two-object fix, so use it as a check."),
 ("What is a transferred position line?",
  "Any earlier position line moved forward along the ground track by the distance made good, so it can be crossed with a later observation. It is the basis of the running fix."),
 ("Why should you never simply steer straight at a waypoint across a strong cross-tide?",
  "Because the autopilot or helm will crab you round a long curve, sailing extra distance and possibly across a hazard on the inside of the curve. Work out the course to steer that makes good the straight track instead."),
 ("What is cross-track error, and what should you do with it?",
  "The plotter's measure of how far you are off the straight line between waypoints, with the side. Use it as a check on your course to steer, but understand it does not know what is on either side of the line — the chart does."),
 ("How do you use a depth contour as a position line?",
  "Compare the echo sounder reading, corrected for the height of tide and the transducer offset, with the charted depth. The moment you cross a distinct contour you are somewhere <b>on that contour</b> — the contour itself is the position line, running in whatever direction the contour runs. Cross it as near square-on as you can so the moment of crossing is sharp, and cross it with a bearing to get a fix. Excellent when visibility fails."),
 ("Two objects give bearings 040&deg;M and 130&deg;M. Variation is 5&deg;W. What do you plot?",
  "Convert each to true by subtracting the westerly variation when going magnetic to true: <b>035&deg;T and 125&deg;T</b>. Plot each line from its object. They are 90&deg; apart, which is an ideal cut."),
 ("Why does a fix from two bearings taken 15&deg; apart deserve suspicion?",
  "Because a small error in either bearing moves the intersection a long way along the lines. Bearings that cut at close to a right angle give the tightest fix; anything under about 30&deg; is unreliable."),
 ("What is 'the six-minute rule' and how do you use it at the chart table?",
  "In six minutes you travel one tenth of your speed in miles — at 6 knots, 0.6 M. It makes quick mental work of the distance run between fixes and of tidal drift over part of an hour."),
 ("You have no GNSS, no visibility and no depth information you trust. What do you do?",
  "Stop making the situation worse. Heave to or slow down,<br>sound the fog signal,<br>work up an EP from the last known fix,<br>plot the danger areas around it,<br>and either stand off into safe deep water or anchor in a shallow area clear of the channel until visibility lifts."),
 ("Track required 090&deg;T, tide sets 180&deg;T at 1.5 kn, boat speed 5 kn, wind from the north giving 5&deg; leeway, variation 4&deg;W, no deviation. What do you steer?",
  "Plot 1.5 M of tide on 180&deg; from the fix;<br>from its end swing 5 M to cut the 090&deg; track.<br>Water track = <b>073&deg;T</b>, SOG = <b>4.8 kn</b>.<br>The wind is from the north, so steer 5&deg; upwind of the water track: heading <b>068&deg;T</b>.<br>Variation 4&deg;W, so 068 + 4 = <b>072&deg;C</b>.", "ds-cts-triangle.png"),
 ("How do you lay off and read a course or bearing with a Portland (Breton) plotter?",
  "To <b>read</b> a line: lay the plotter's edge along it, rotate the rose until its grid lines are parallel with a meridian and the arrow points to the top of the chart, and read the true bearing. To <b>plot</b>: set the bearing on the rose first, then slide the plotter until the grid is parallel with a meridian and the edge passes through the object. Distance is separate — dividers on the <b>latitude</b> scale."),
 ("How do you plot 50&deg;38'.4 N 001&deg;33'.6 W on the chart?",
  "Set the dividers to 38'.4 on the latitude scale at the side, step in from the nearest printed parallel and pencil a short line; set them to 33'.6 on the longitude scale at the top or bottom and step in from the nearest meridian, using a straight edge or plotter. The position is the crossing. Check the hemisphere, and that the minutes increase in the direction you expect."),
 ("Your leg will take 40 minutes. What do you put in the course-to-steer triangle?",
  "Vectors for the <b>same period</b>: 40 minutes of tide, so rate &times; 40/60, and 40 minutes of boat speed. Any period works so long as both use it. Over more than an hour, or where the stream changes, work hour by hour or use the resultant of each hour's tide.", "ds-cts-triangle.png"),
]),

("tides", "12 Tides and tidal heights", [
 ("What causes tides?",
  "The gravitational pull of the moon and, to a lesser extent, the sun on the oceans, plus the centrifugal effect of the earth-moon system. The moon dominates, so the tidal day is about 24 h 50 min and there are usually two high waters a day, roughly 12 h 25 min apart."),
 ("What are spring and neap tides, and when do they occur?",
  "<b>Springs</b> — the sun and moon pull in line at new and full moon, giving the largest range: highest highs and lowest lows.<br><b>Neaps</b> — at the first and last quarter the pulls are at right angles, giving the smallest range. There is a lag of about two days after the phase of the moon."),
 ("Define chart datum and say what UK charts use.",
  "The level from which charted depths and drying heights are measured. On UK Admiralty charts it is approximately <b>Lowest Astronomical Tide (LAT)</b>, the lowest level predictable under average meteorological conditions, so the sea very rarely falls below the charted depth.", "ds-tidal-datums.png"),
 ("What are MHWS, MHWN, MLWN and MLWS?",
  "Mean High Water Springs, Mean High Water Neaps, Mean Low Water Neaps and Mean Low Water Springs — the average heights above chart datum of high and low waters at springs and neaps.", "ds-tidal-datums.png"),
 ("What is the height of tide, and what is the range?",
  "The <b>height of tide</b> is the height of the sea surface above chart datum at a given moment. The <b>range</b> is the difference between the heights of successive high and low waters.", "ds-tidal-datums.png"),
 ("What is the depth of water at a place?",
  "Charted depth + height of tide.", "ds-tidal-datums.png"),
 ("How much water is there over a patch that dries 1.8 m when the height of tide is 4.2 m?",
  "Height of tide &minus; drying height = 4.2 &minus; 1.8 = <b>2.4 m</b>.", "ds-tidal-datums.png"),
 ("How do you work out clearance under the keel?",
  "Charted depth + height of tide &minus; draught. Then subtract a safety margin for swell, squat, chart accuracy and barometric effect before you decide to go.", "ds-tidal-datums.png"),
 ("What datum are charted heights and vertical clearances measured from?",
  "Heights of <b>lights, beacons and land features</b> are above <b>MHWS</b>. <b>Vertical clearances</b> under bridges and overhead cables are above <b>HAT</b> on new-edition Admiralty charts and MHWS on older ones — the title block says which. Real clearance = charted clearance + the height datum &minus; height of tide, which is normally <b>more</b> than the charted figure.", "ds-tidal-datums.png"),
 ("State the rule of twelfths.",
  "Between low and high water the tide rises by 1, 2, 3, 3, 2 then 1 twelfths of the range in each successive sixth of the tidal duration.", "ds-rule-of-twelfths.png"),
 ("LW 1.2 m at 0600, HW 5.4 m at 1215. Estimate the height at 0900.",
  "Range 5.4 &minus; 1.2 = 4.2 m, so a twelfth is 0.35 m. Duration 6 h 15 min, so each sixth is 62&frac12; min. 0900 is 180 min after LW, which is 2.9 sixths — call it 3. Risen 1+2+3 = 6 twelfths = 2.1 m, so the height is 1.2 + 2.1 = <b>about 3.3 m</b> above chart datum.", "ds-rule-of-twelfths.png"),
 ("What are the limitations of the rule of twelfths?",
  "It assumes a symmetrical, roughly sinusoidal curve and a six-hour rise. It is unreliable where the curve is distorted — the Solent and Poole with their double high waters, the Thames, and many rivers and estuaries. For anything tight use the tidal curve.", "ds-rule-of-twelfths.png"),
 ("Describe how you use a standard port tidal curve to find the height at a given time.",
  "Take HW and LW times and heights from the tables.<br>Fill in the hour boxes with HW time in the centre.<br>Draw the sloping line joining the LW height on the lower scale to the HW height on the upper scale.<br>Enter the graph at the time wanted, go up to the curve (spring, neap, or interpolated by range), across to the sloping line, then up or down to the height scale — the top and bottom scales are the same graduation.<br>Check the diagram's reference: a few ports, including Portland, Poole and Christchurch, have curves drawn about <b>LW</b>, so the centre box is LW time.", "ds-tidal-curve.png"),
 ("How do you use the tidal curve the other way — to find the time at which a given height occurs?",
  "Enter at the height on the sloping line, go up (or down) to the curve, then across to the time scale. Do it for both the rise and the fall to get the window during which you have enough water.", "ds-tidal-curve.png"),
 ("Which curve do you use when the range is between springs and neaps?",
  "Interpolate between the spring and neap curves in proportion to the day's actual range compared with the mean spring and mean neap ranges printed on the diagram.", "ds-tidal-curve.png"),
 ("What is a standard port and what is a secondary port?",
  "A <b>standard port</b> has its own full tide tables and tidal curve. A <b>secondary port</b> is worked out from a nominated standard port by applying tabulated <b>time differences</b> and <b>height differences</b> from the almanac."),
 ("How do you work out HW time and height at a secondary port?",
  "Take the standard port's HW time and height.<br>The table gives time differences at two tabulated HW times: interpolate between them on the standard port's <b>actual HW time</b>.<br>It gives height differences at the standard port's MHWS and MHWN (and MLWN and MLWS): interpolate on the standard port's <b>actual height</b>.<br>Apply both differences.<br>Then work the height on the <b>standard port's curve</b>, with the secondary port's HW time in the centre box and its own HW and LW heights on the scales, unless the almanac prints a curve for the secondary port itself."),
 ("What does 'the tide is making' or 'the tide is taking off' mean?",
  "<b>Making</b> — the ranges are increasing day by day towards springs.<br><b>Taking off</b> — the ranges are decreasing towards neaps."),
 ("What is the difference between a tidal gate and a tidal window?",
  "A <b>tidal gate</b> is a place you can only pass at certain states of tide — a race, an overfall, a bridge, a sill, a bar. A <b>tidal window</b> is the span of time during which you have enough depth or a fair stream to do so. Plan the passage around the gates."),
 ("What is a sill, and what must you check before entering a marina with one?",
  "A wall across the entrance that retains water inside at low tide. Check the height of the sill above chart datum,<br>your draught,<br>and the height of tide at your arrival and departure times,<br>and remember you may be locked in as well as out."),
 ("What effects can make the actual tide differ from the prediction?",
  "<b>Barometric pressure</b> — roughly 0.01 m per millibar of departure from <b>1013 mb</b>, so 30 mb below it raises the level about 0.3 m and a high depresses it; <b>strong or prolonged wind</b> can pile water up on a coast (a surge) or hold it back; heavy river flow raises levels in an estuary. Never plan on the last 0.2 m."),
 ("Why is the ebb usually more dangerous than the flood for a small yacht?",
  "The ebb runs out against the prevailing swell over shoals and bars, steepening and breaking the seas, and it takes you offshore away from shelter if you break down. Many harbour bars are only safe on the flood."),
 ("Where do you find the time zone of a set of tide tables, and why does it matter?",
  "In the heading of the table — UK Admiralty tables are in <b>UT (GMT)</b>. In British Summer Time you must <b>add one hour</b> to every tabulated time. Getting this wrong is the single most common tidal error."),
 ("Which tidal curve do you use for a secondary port?",
  "The <b>standard port's</b> curve, unless the almanac prints one for the secondary port itself. Work out the secondary port's HW and LW times and heights first, then put its HW time in the centre box and its own HW and LW heights on the height scales. Choose the spring or neap curve, or interpolate, on the <b>standard port's</b> range.", "ds-tidal-curve.png"),
 ("You draw 1.8 m and want 1.0 m under the keel to cross a bar charted at 0.6 m. What height of tide do you need, and how do you find the window?",
  "Required height of tide = draught + clearance &minus; charted depth = 1.8 + 1.0 &minus; 0.6 = <b>2.2 m</b>. Enter the tidal curve at 2.2 m on the sloping line, read across to the curve and down to the time scale on both the rise and the fall: the span between those two times is your <b>tidal window</b>.", "ds-tidal-curve.png"),
 ("What are LAT and HAT, and where does each appear?",
  "<b>Lowest</b> and <b>Highest Astronomical Tide</b> — the extreme levels predictable under average meteorological conditions and any combination of astronomical conditions. Chart datum is at approximately <b>LAT</b>, so charted depths are almost never overstated. Vertical clearances under bridges and cables on new-edition Admiralty charts are above <b>HAT</b>. Neither is a limit the weather cannot beat.", "ds-tidal-datums.png"),
]),

("streams", "13 Tidal streams", [
 ("What is the difference between a tidal stream and a current?",
  "A <b>tidal stream</b> is the horizontal flow of water caused by the tide; it reverses predictably. A <b>current</b> is a non-tidal flow driven by wind, river outflow or ocean circulation, and it does not reverse."),
 ("Define set and drift, and rate.",
  "<b>Set</b> is the direction the stream flows <b>towards</b>, in degrees true. <b>Rate</b> is its speed in knots. <b>Drift</b> is the distance the stream carries you over a stated period."),
 ("How do you read a tidal diamond table?",
  "Find the diamond letter on the chart, then in the almanac read the row for the hour relative to HW at the named reference port. It gives the set in degrees true, and the rate for springs and for neaps. Interpolate for the actual range."),
 ("A tidal stream atlas arrow reads 19,34. What does that mean?",
  "The rate is <b>1.9 knots at neaps and 3.4 knots at springs</b> in the direction of the arrow, for that hour relative to HW at the atlas's reference port."),
 ("How do you get the actual rate when the day is neither springs nor neaps?",
  "Interpolate between the neap and spring figures in proportion to the day's range compared with the mean neap and mean spring ranges. Many almanacs print a computation-of-rates diagram to do this graphically."),
 ("Where do tidal streams run fastest?",
  "Where the flow is squeezed: round headlands,<br>through narrows and channels,<br>over shallow banks,<br>and between islands. Streams are weaker in bays and close inshore, which is why you cheat the tide in the shallows."),
 ("What is a tidal race and an overfall?",
  "Disturbed, steep and breaking water where a strong stream runs over an uneven bottom or round a headland, or where two streams meet. It can be dangerous out of proportion to the wind strength. Avoid it, or time your passage for slack water and a fair wind."),
 ("What happens when wind and tide oppose one another?",
  "The waves become steeper, shorter and more likely to break — 'wind against tide'. The same wind with the tide gives a longer, easier sea. A gale against a spring ebb over a shoal is genuinely dangerous."),
 ("What is a lee-bow tide and why do skippers like it?",
  "A tidal stream setting onto the leeward bow. The tide's vector is the same whichever tack you are on, so it is not free windward gain — the point is that on the lee-bow tack the stream carries you <b>towards</b> your windward objective rather than away from it, and the boat sails a heading closer to the track you need. When beating, work the tack that puts the tide on the lee bow."),
 ("What is slack water, and does it coincide with high water?",
  "The short period when the stream is not running. It does <b>not</b> necessarily coincide with HW or LW: in some places the stream turns close to local high and low water, in others nearer mid-tide, and the difference can be two to three hours. Always take the timing from the tidal stream atlas or the diamond, referenced to HW at the named port — never guess it from the tide table."),
 ("Why should you plan a passage around the tidal stream and not just the wind?",
  "Because 2 knots of stream on a 5 knot boat is 40% of your speed: fair tide gives 7 knots over the ground, foul gives 3. Over a six-hour tide that is the difference between arriving and not."),
 ("How do you work out the total tidal effect over a three-hour passage?",
  "Take the set and rate for each of the three hours from the diamonds or atlas, and either plot them end to end as three successive vectors or resolve them into one resultant vector for the whole period. Then use that resultant in the course-to-steer triangle."),
 ("What is the practical difference between working out a course to steer hour by hour and for the whole passage?",
  "Hour by hour keeps you close to the intended track throughout, which matters if there are dangers either side. A single resultant for the whole leg gets you to the destination but lets you wander well off the straight line in between — fine in open water, wrong in confined water."),
 ("Why does a strong tidal stream matter when you pick up a mooring or come alongside?",
  "Because the boat steers by water flow, not ground speed. Approach into the stronger of wind and tide so you have steerage way at a low speed over the ground, and remember you will stop much faster with the tide against you than with it behind you."),
]),

("buoyage", "14 IALA buoyage", [
 ("What is a port hand mark in IALA Region A?",
  "<b>Red</b>, can (cylindrical) shape, with a red can topmark if any, showing a <b>red light of any rhythm except Fl(2+1)R</b>, which is reserved for the preferred-channel mark — for example Fl R 5s. Keep it to <b>port</b> when travelling in the direction of buoyage.", "ds-iala-lateral.png"),
 ("What is a starboard hand mark in IALA Region A?",
  "<b>Green</b>, conical shape, with a green cone topmark point up if any, showing a <b>green light of any rhythm except Fl(2+1)G</b>, which is reserved for the preferred-channel mark — for example Fl G 3s. Keep it to <b>starboard</b> in the direction of buoyage.", "ds-iala-lateral.png"),
 ("What is the direction of buoyage?",
  "The direction a vessel takes when approaching a harbour, river or estuary from seaward, or elsewhere the direction shown on the chart by a broad arrow symbol. The general convention is clockwise around continental land masses. <b>Around the British Isles it runs north up the west coast and through the Irish Sea, east through the English Channel, and north through the North Sea</b> — so it is not a clockwise circuit of the islands.", "ds-iala-lateral.png"),
 ("How do the lateral colours differ between IALA Region A and Region B?",
  "The colours are <b>reversed</b>: in Region B (the Americas, Japan, Korea, the Philippines) port hand is <b>green</b> and starboard hand is <b>red</b>. Shapes and topmarks are unchanged. 'Red right returning' is a Region B rule and is wrong in the UK.", "ds-iala-lateral.png"),
 ("Describe a preferred channel to starboard mark in Region A.",
  "<b>Red with a single broad green horizontal band</b>, can shape, light <b>Fl(2+1) R</b>. It marks a channel division; treat it as a <b>port hand</b> mark for the main channel, which lies to starboard of it.", "ds-iala-lateral.png"),
 ("Describe a preferred channel to port mark in Region A.",
  "<b>Green with a single broad red horizontal band</b>, conical shape, light <b>Fl(2+1) G</b>. Treat it as a <b>starboard hand</b> mark; the main channel lies to port of it.", "ds-iala-lateral.png"),
 ("Describe the North cardinal mark.",
  "<b>Black above yellow</b>. Topmark: two black cones both pointing <b>up</b>. Light: <b>Q</b> or <b>VQ</b>, white. Pass to the <b>north</b> of it — safe water lies north of the mark.", "ds-cardinal-marks.png"),
 ("Describe the East cardinal mark.",
  "<b>Black, yellow band, black</b>. Topmark: two black cones <b>base to base</b>. Light: <b>Q(3) 10s</b> or VQ(3) 5s, white. Pass to the <b>east</b> of it.", "ds-cardinal-marks.png"),
 ("Describe the South cardinal mark.",
  "<b>Yellow above black</b>. Topmark: two black cones both pointing <b>down</b>. Light: <b>Q(6) + LFl 15s</b> or VQ(6) + LFl 10s, white — the long flash confirms you counted six. Pass to the <b>south</b> of it.", "ds-cardinal-marks.png"),
 ("Describe the West cardinal mark.",
  "<b>Yellow, black band, yellow</b>. Topmark: two black cones <b>point to point</b>, like a wine glass. Light: <b>Q(9) 15s</b> or VQ(9) 10s, white. Pass to the <b>west</b> of it.", "ds-cardinal-marks.png"),
 ("What is the memory aid for cardinal light rhythms?",
  "A clock face: East is 3 o'clock so 3 flashes;<br>South is 6 o'clock so 6 flashes plus a long flash;<br>West is 9 o'clock so 9 flashes;<br>North is 12 o'clock so continuous quick flashing.", "ds-cardinal-marks.png"),
 ("What are the cardinal quadrant boundaries?",
  "NW, NE, SE and SW — true bearings 315&deg;, 045&deg;, 135&deg; and 225&deg;, measured <b>from the danger</b>.", "ds-cardinal-marks.png"),
 ("Describe an isolated danger mark.",
  "<b>Black with one or more broad red horizontal bands</b>, topmark <b>two black spheres</b> in a vertical line, light <b>Fl(2) white</b>. It is moored <b>on or above</b> a small isolated danger that has navigable water all round it.", "ds-other-marks.png"),
 ("Describe a safe water mark.",
  "<b>Red and white vertical stripes</b>,<br>spherical or with a single <b>red sphere</b> topmark,<br>light white: <b>Iso, Oc, LFl 10s or Mo(A)</b>. There is navigable water all round it. Often used as a mid-channel or landfall mark.", "ds-other-marks.png"),
 ("Describe a special mark.",
  "<b>Yellow</b>,<br>any shape not conflicting with a navigational mark,<br>topmark a single <b>yellow X</b>,<br>light <b>yellow</b>, in any rhythm <b>except those used for the white lights of cardinal, isolated danger and safe water marks</b>. It marks a special area or feature —<br>spoil ground,<br>outfall,<br>cables,<br>military exercise area,<br>recreation zone,<br>racing marks,<br>ODAS buoys.", "ds-other-marks.png"),
 ("Describe the emergency wreck marking buoy.",
  "<b>Blue and yellow vertical stripes</b>, topmark a yellow upright <b>cross</b>, light <b>alternating blue and yellow, Al Oc BuY 3s</b>. It is deployed on a newly discovered wreck until the wreck is charted and permanently marked.", "ds-other-marks.png"),
 ("What is the difference between an isolated danger mark and a safe water mark in practice?",
  "The isolated danger mark sits <b>on</b> the hazard — never pass close to it. The safe water mark has deep water all round and may be passed on either side.", "ds-other-marks.png"),
 ("What does a yellow buoy with a yellow X topmark near an outfall tell you?",
  "It is a special mark: not a navigational hazard mark in itself, but there is something there — a pipeline, cable or restricted area. Look it up on the chart before you cut inside it."),
 ("How is a small-craft channel or a recommended track for yachts often marked?",
  "By small buoys, sometimes yellow special marks, or by charted small-craft channels outside the main fairway. Harbour byelaws often require small craft to use them and to keep clear of the deep-water channel."),
 ("What is a withy or a perch?",
  "A local, unofficial or simple mark — a bundle of twigs or a pole — used in creeks and shallow channels. They may follow local convention rather than IALA and are not always charted, so treat them with care and read the pilot book."),
 ("How can you tell a lit buoy from an unlit one on the chart?",
  "A lit buoy carries a magenta flare symbol and the light's characteristic, e.g. 'Fl G 5s'. No flare means unlit — which matters enormously if you plan to arrive after dark."),
 ("You see a buoy with a black body, a red band and two black spheres. What is it and what do you do?",
  "An isolated danger mark: there is a hazard right there with navigable water round it. Identify it on the chart, work out which side gives you the room you need, and give it a wide berth.", "ds-other-marks.png"),
 ("Which lights and marks does the IALA buoyage system NOT apply to?",
  "Landfall lights,<br>leading lights and marks,<br>sector lights,<br>and major floating lights. They keep their own charted characteristics — so a red light in an approach is not necessarily a port-hand buoy."),
 ("What is a 'new danger', and how is it marked?",
  "An uncharted hazard — wreck, rock or shoal — not yet promulgated in nautical publications. It is marked with lateral, cardinal or isolated danger marks, or with an emergency wreck marking buoy. One of the marks may be <b>duplicated</b> until the danger is charted, and it may carry a racon showing Morse <b>D</b> and an AIS transponder.", "ds-other-marks.png"),
 ("In Region B, what is a green buoy with a red band showing Fl(2+1) G?",
  "A <b>preferred channel to starboard</b> mark. In Region B green is the port-hand colour, so the preferred-channel colours and rhythms swap over: Fl(2+1)G marks a preferred channel to starboard and Fl(2+1)R a preferred channel to port.", "ds-iala-lateral.png"),
 ("What are the standard buoy shapes, and when does shape tell you nothing?",
  "Can (cylindrical),<br>conical,<br>spherical,<br>pillar<br>and spar. On pillar and spar buoys — and on all fixed beacons — only the <b>topmark and colour</b> have navigational significance, because the body shape is dictated by the structure."),
 ("Apart from which side to pass, what else can a cardinal mark be telling you?",
  "Where the best navigable water lies;<br>the safe side on which to pass a danger;<br>or a feature in a channel — a bend, a junction, a branch, or the end of a shoal.", "ds-cardinal-marks.png"),
]),

("lightchar", "15 Light characteristics", [
 ("What does F mean on a chart?",
  "Fixed — a continuous, steady light that does not change.", "ds-light-characteristics.png"),
 ("What does Fl mean, and what is the pattern?",
  "Flashing — a single flash at regular intervals, where the duration of <b>light is shorter</b> than the duration of dark. Fl 5s = one flash every 5 seconds.", "ds-light-characteristics.png"),
 ("What does Fl(3) 15s mean?",
  "Group flashing — a group of <b>three</b> flashes, the whole pattern repeating every <b>15 seconds</b>.", "ds-light-characteristics.png"),
 ("What does LFl mean?",
  "Long flashing — a single flash of <b>2 seconds or more</b>, repeated. LFl 10s = one long flash every 10 seconds.", "ds-light-characteristics.png"),
 ("What does Oc mean, and how do you recognise it?",
  "Occulting — the <b>light is longer than the dark</b>: a steady light briefly eclipsed. Oc(2) 7s = two eclipses in a 7-second period.", "ds-light-characteristics.png"),
 ("What does Iso mean?",
  "Isophase — the periods of light and dark are <b>exactly equal</b>.", "ds-light-characteristics.png"),
 ("What do Q and VQ mean?",
  "<b>Q</b> quick flashing, 50-79 flashes per minute.<br><b>VQ</b> very quick flashing, 80-159 per minute. (UQ, ultra quick, is 160 or more.)", "ds-light-characteristics.png"),
 ("What does Mo(A) mean, and where would you see it?",
  "Morse code letter A — a short flash followed by a long flash. Commonly used on <b>safe water marks</b> and landfall buoys.", "ds-light-characteristics.png"),
 ("What does Al mean?",
  "Alternating — the light shows different colours in succession from the same position, e.g. Al WR.", "ds-light-characteristics.png"),
 ("What is the 'period' of a light?",
  "The time taken for one complete cycle of the light's pattern, from the start of one group to the start of the next. It is the number of seconds printed after the rhythm, and it is what you actually time with a watch to identify a light.", "ds-light-characteristics.png"),
 ("Decode: Fl(2)WRG 10s 15m 11-8M.",
  "Two flashes every 10 seconds;<br>the light shows <b>white, red and green sectors</b>;<br>its elevation is <b>15 m above the chart height datum</b>, which is MHWS on UK charts;<br>and the nominal ranges are <b>white 11 M, green 8 M, red between the two</b> — the first figure is always white and the last green."),
 ("Decode: Oc(2)R 7s 9m 6M.",
  "An occulting red light, two eclipses in a 7-second period, 9 metres above MHWS, nominal range 6 miles."),
 ("Decode: Q(9) 15s.",
  "Nine quick flashes every 15 seconds — a <b>West cardinal</b> mark.", "ds-cardinal-marks.png"),
 ("Decode: Fl(2+1) R 10s.",
  "A group of two flashes then a single flash, red, every 10 seconds — a <b>preferred channel to starboard</b> mark in Region A.", "ds-iala-lateral.png"),
 ("If a light shows no colour letter, what colour is it?",
  "White. Colours are lettered only when they are not white: R red,<br>G green,<br>Y yellow,<br>Bu blue,<br>Vi violet,<br>Or orange."),
 ("How do you positively identify a light at night?",
  "Time the full period with a watch, count the flashes in a group, note the colour, and compare all three with the chart or light list. Then check the bearing is consistent with your expected position. Never identify a light on colour alone."),
 ("What is a lighthouse's 'racon' marking on the chart?",
  "A radar transponder beacon: it paints a Morse identification letter on a radar display outward from its position, giving a range and bearing. Charted as 'Racon(T)' or similar."),
 ("What does IQ mean?",
  "Interrupted quick flashing — continuous quick flashing with a regular eclipse. IVQ and IUQ are the very quick and ultra quick equivalents.", "ds-light-characteristics.png"),
 ("What does FFl mean?",
  "Fixed and flashing — a steady light with a brighter flash superimposed at regular intervals.", "ds-light-characteristics.png"),
 ("On an Admiralty chart, what is a light's elevation measured from, and what does its charted range mean?",
  "Elevation is the height of the <b>focal plane above the chart's height datum</b> — MHWS on UK charts — not above the sea level at the time.<br>Charted ranges are <b>nominal ranges</b> in sea miles: the luminous range in a meteorological visibility of 10 sea miles."),
 ("A light is charted 'Fl WRG 5s 12m 11-8M'. What is the range of each colour?",
  "<b>White 11 M, green 8 M, red between the two.</b> The first figure is always white and the last is green; intermediate colours lie between."),
 ("For a sector light or a leading line, which way are the charted bearings measured?",
  "<b>Always from seaward</b>, towards the light. To use one as a course to steer inbound you read it straight off the chart; to leave on it you use the reciprocal."),
]),

("meteo", "16 Meteorology", [
 ("What is the Beaufort scale, and what are forces 4, 6 and 8 called?",
  "A scale of wind force from 0 to 12 based on observed sea state. Force 4 is a <b>moderate breeze</b>, 11-16 knots;<br>force 6 a <b>strong breeze</b>, 22-27 knots;<br>force 8 a <b>gale</b>, 34-40 knots.", "ds-beaufort.png"),
 ("What are the wind speeds for Beaufort forces 5, 7 and 9?",
  "Force 5 fresh breeze <b>17-21 kn</b>;<br>force 7 near gale <b>28-33 kn</b>;<br>force 9 <b>strong gale 41-47 kn</b> — which is the name on the Beaufort scale, though gale warnings and the shipping forecast call it <b>severe gale 9</b>.", "ds-beaufort.png"),
 ("At what force do you expect to see 'many white horses' and think about the first reef?",
  "Force 5, a fresh breeze of 17-21 knots: moderate waves, many white horses, some spray. Most cruising yachts want the first reef in at the top of force 4 or in force 5.", "ds-beaufort.png"),
 ("What do the shipping forecast terms 'gale', 'severe gale', 'storm' and 'violent storm' mean?",
  "<b>Gale</b> — mean wind force 8, or gusts of 43-51 kn.<br><b>Severe gale</b> — force 9, or gusts 52-60 kn.<br><b>Storm</b> — force 10, or gusts 61-68 kn.<br><b>Violent storm</b> — force 11, or gusts of 69 kn or more.", "ds-beaufort.png"),
 ("What do 'imminent', 'soon' and 'later' mean in a shipping forecast gale warning?",
  "<b>Imminent</b> — within 6 hours of the time of issue.<br><b>Soon</b> — 6 to 12 hours.<br><b>Later</b> — more than 12 hours.", "ds-beaufort.png"),
 ("Define the marine visibility terms good, moderate, poor and very poor.",
  "<b>Good</b> — more than 5 nautical miles.<br><b>Moderate</b> — 2 to 5 M.<br><b>Poor</b> — 1,000 m to 2 M.<br><b>Very poor</b> — less than 1,000 m.<br><b>Fog</b> is a term in the weather element rather than a visibility band, and fog means visibility below 1,000 m.", "ds-beaufort.png"),
 ("Define the pressure-tendency terms used in the shipping forecast.",
  "Change in the 3 hours before the observation, in hPa (1 hPa = 1 mb): <b>rising or falling slowly</b> 0.1-1.5;<br><b>rising or falling</b> 1.6-3.5;<br><b>rising or falling quickly</b> 3.6-6.0;<br><b>rising or falling very rapidly</b> more than 6.0. Also <b>rising or falling more slowly</b>, meaning the rate is easing, and <b>now rising</b> or <b>now falling</b>, meaning it has just turned. <b>Steady</b> means no appreciable change.", "ds-beaufort.png"),
 ("What do 'backing' and 'veering' mean?",
  "<b>Backing</b> — the wind direction changes <b>anticlockwise</b>, e.g. SW to S.<br><b>Veering</b> — it changes <b>clockwise</b>, e.g. SW to NW. In the northern hemisphere the wind veers as each front passes.", "ds-fronts.png"),
 ("Which direction is a wind named for?",
  "The direction it blows <b>from</b>. A westerly wind blows from the west. A tidal stream, by contrast, is named for the direction it flows <b>towards</b>."),
 ("What are the parts of the shipping forecast, in order?",
  "Gale warnings;<br>the general synopsis, meaning where the pressure systems are and where they are going;<br>then for each sea area in turn: <b>wind direction and force, sea state, weather, visibility</b>.<br>Then reports from coastal stations, and on some broadcasts the inshore waters forecast. It is issued four times a day and covers 24 hours."),
 ("Where can you get a marine forecast at sea?",
  "Met Office shipping and inshore waters forecasts on <b>BBC Radio 4 FM, DAB and BBC Sounds</b> — the 198 kHz long wave transmission closed on 27 June 2026;<br>Maritime Safety Information broadcasts by HM Coastguard on VHF (announced on Ch 16, given on a working channel);<br>NAVTEX on 518 kHz;<br>the Met Office and other websites and apps by mobile data;<br>harbour offices and marina noticeboards;<br>and barometer plus your own eyes."),
 ("How does a depression behave in the northern hemisphere?",
  "Pressure is lowest at the centre, wind circulates <b>anticlockwise</b> and blows slightly inwards across the isobars, and the system usually tracks east or north-east. Closely spaced isobars mean strong wind.", "ds-fronts.png"),
 ("How does an anticyclone behave in the northern hemisphere?",
  "High pressure with <b>clockwise</b> circulation and light winds, widely spaced isobars, settled weather. In summer it brings fine weather and sea breezes; in winter it can bring fog, low cloud and frost. Anticyclones move slowly and block depressions."),
 ("State Buys Ballot's law.",
  "In the northern hemisphere, if you stand with your back to the wind, low pressure is on your <b>left</b>. It lets you place the depression without a chart.", "ds-fronts.png"),
 ("What is a warm front and what weather does it bring?",
  "The boundary where warm air rides up over cold air. Ahead of it:<br>high cirrus thickening to altostratus and then low, thick cloud,<br>pressure falling steadily,<br>a long spell of continuous rain,<br>and the wind increasing — <b>backing as the depression first approaches, then veering through the frontal zone</b>. As the front passes the rain eases to drizzle, the wind <b>veers</b>, pressure steadies and the temperature rises.", "ds-fronts.png"),
 ("What is a cold front and what weather does it bring?",
  "Cold air undercutting warm air, giving a sharp, often squally transition:<br>towering cumulonimbus,<br>heavy showers or thunder,<br>a marked <b>veer</b> and gusting of the wind,<br>a sharp rise in pressure and a drop in temperature. Behind it the air is clear, bright and showery with good visibility.", "ds-fronts.png"),
 ("What is the warm sector like?",
  "The area between the warm and cold fronts:<br>overcast with low stratus,<br>drizzle,<br>mild and muggy,<br><b>poor visibility</b> and often sea fog,<br>with steady pressure and a steady wind direction.", "ds-fronts.png"),
 ("What is an occlusion?",
  "Where the cold front catches up with the warm front and lifts the warm sector clear of the surface. You get the cloud and rain of both fronts combined, but without the clear temperature change — a wet, murky passage of weather.", "ds-fronts.png"),
 ("What is the classic sequence of wind and pressure as a depression passes to your north?",
  "Starting from a south-westerly gradient wind: as the depression approaches from the west the wind <b>backs to SE</b> and freshens while pressure falls;<br>the warm front passes and the wind <b>veers to SW</b>, pressure steadies and visibility worsens;<br>the cold front passes and the wind <b>veers sharply to NW</b> and gusts, pressure rises and visibility clears. <b>At each front the wind veers.</b>", "ds-fronts.png"),
 ("What is a trough and a ridge?",
  "A <b>trough</b> is an elongated area of low pressure — expect a wind shift, cloud and showers even without a named front.<br>A <b>ridge</b> is an elongated area of high pressure, bringing a temporary improvement."),
 ("What is a sea breeze, and when should you expect one?",
  "On a sunny day the land heats faster than the sea, air rises over the land and cooler sea air flows in. It typically starts late morning,<br>blows onshore,<br>can reach force 4-5 by mid-afternoon and dies in the evening. It needs a sunny day and a light background wind, and it can reinforce or cancel the gradient wind."),
 ("What is a land breeze?",
  "The night-time reverse: the land cools faster than the sea, so a light offshore breeze flows from land to sea in the early hours. It is usually weaker than the sea breeze."),
 ("What is advection fog (sea fog) and why does it matter to a yacht?",
  "Warm, moist air moving over a colder sea surface is cooled below its dew point. It can form in a good breeze, persist for days, and it is the fog that catches yachts out in spring and early summer in the Channel — thickest often in the warm sector of a depression."),
 ("What is radiation fog?",
  "Fog formed overnight over land by radiative cooling under clear skies with light winds. It drifts out of estuaries and harbour entrances at dawn and usually burns off during the morning."),
 ("How does the barometer help you if you have no forecast?",
  "The trend matters more than the value. Falling steadily means a depression approaching: wind and rain. Falling <b>quickly</b>, 3.6-6.0 hPa in 3 hours, or <b>very rapidly</b>, more than 6.0 hPa in 3 hours, means a vigorous system and possibly gale-force wind. Rising means improvement, though a sharp rise behind a cold front comes with squalls."),
 ("What clouds warn you of a squall or thunderstorm?",
  "<b>Cumulonimbus</b> — tall, dark, anvil-topped. Expect a sudden violent wind shift and increase,<br>heavy rain or hail,<br>and a rapid drop in visibility. Reef before it arrives and get the crew clipped on."),
 ("What is a katabatic wind and where might you meet one?",
  "Cold dense air draining down a slope at night, producing a strong offshore gust that arrives without warning in a sheltered-looking anchorage under high ground — common in the Mediterranean, Norway and steep-sided lochs."),
 ("How does the wind behave near a headland or a cliff?",
  "It accelerates and bends round headlands, giving a stronger gust and a wind shift; under a cliff there may be a wind shadow, and then violent downdraughts and gusts a few boat lengths further out. Never assume the wind close inshore is the forecast wind."),
 ("What does 'fog patches' or 'occasionally poor' mean in an inshore waters forecast?",
  "It is a qualifier, not a promise: the poor visibility or fog is expected for <b>part of the period only, and not everywhere in the area</b>. The Met Office publishes no numerical definition of 'occasional' or 'patches'. Plan as if you will get it, and know where you can go if it closes in."),
 ("What is the difference between the shipping forecast and the inshore waters forecast?",
  "The shipping forecast covers the large sea areas offshore with mean winds and a 24-hour outlook. The <b>inshore waters</b> forecast covers up to 12 miles off the coast in more relevant detail — wind, weather, visibility, sea state — and is the one a Day Skipper should be using."),
 ("What sea state terms are used, and what do they mean?",
  "<b>Calm (glassy)</b> 0 m;<br><b>calm (rippled)</b> 0-0.1 m;<br><b>smooth</b> 0.1-0.5 m;<br><b>slight</b> 0.5-1.25 m;<br><b>moderate</b> 1.25-2.5 m;<br><b>rough</b> 2.5-4 m;<br><b>very rough</b> 4-6 m;<br><b>high</b> 6-9 m;<br><b>very high</b> 9-14 m;<br><b>phenomenal</b> more than 14 m. These are significant wave heights — individual waves can be substantially higher."),
 ("How should the forecast affect your go / no-go decision?",
  "Compare the forecast wind and sea with the limits of the <b>boat</b>, the <b>crew</b> (the least experienced person aboard) and the <b>passage</b>, including wind against tide, the exposure of the route and the state of the bar or entrance on arrival. If the answer is marginal for any of the three, do not go."),
 ("What are Beaufort forces 0 to 3?",
  "Force 0 <b>calm</b>, under 1 kn;<br>force 1 <b>light air</b>, 1-3 kn;<br>force 2 <b>light breeze</b>, 4-6 kn;<br>force 3 <b>gentle breeze</b>, 7-10 kn.", "ds-beaufort.png"),
 ("What are Beaufort forces 10, 11 and 12?",
  "Force 10 <b>storm</b>, 48-55 kn;<br>force 11 <b>violent storm</b>, 56-63 kn;<br>force 12 <b>hurricane force</b>, 64 kn or more.", "ds-beaufort.png"),
 ("What does 'hurricane force' mean in a forecast, and why not just 'hurricane'?",
  "Winds of force 12, 64 knots or more. The Met Office says <b>hurricane force</b> because <b>hurricane</b> on its own means a true tropical cyclone, which is not experienced in British waters."),
 ("What is a strong wind warning, and why does it matter more to you than a gale warning?",
  "A warning of winds of <b>force 6 or more</b> in inshore waters. It is issued well below gale force, and force 6 is the threshold at which most small craft should think again — so it is the warning a Day Skipper should act on."),
 ("What do 'slowly', 'steadily', 'rather quickly', 'rapidly' and 'very rapidly' mean about a pressure system?",
  "How fast the system is <b>moving</b>: slowly under 15 kn;<br>steadily 15-25 kn;<br>rather quickly 25-35 kn;<br>rapidly 35-45 kn;<br>very rapidly more than 45 kn. Do not confuse these with the pressure-tendency terms, which describe how fast the barometer is changing."),
 ("What does 'becoming cyclonic' mean in a forecast?",
  "There will be a <b>considerable change of wind direction across the path of a depression</b> within that area — a low is passing through, so expect the wind to swing right round rather than settle."),
 ("What is in the coastal station reports, and what are they for?",
  "Actual observations, not forecasts:<br><b>wind direction and force,<br>visibility,<br>sea-level pressure and pressure tendency</b>. Use them to check the forecast against reality, and to see where the system has actually got to."),
 ("How much stronger than the mean wind are the gusts, and what should you plan for?",
  "Typically 40 to 60% above the mean — one to two Beaufort forces. A forecast force 6 can gust force 8, which is why warnings quote gust bands. <b>Reef for the gusts, not the mean.</b>", "ds-beaufort.png"),
 ("How can you anticipate sea fog before you sail?",
  "Compare the forecast <b>dew point</b> with the <b>sea temperature</b>: if the air's dew point is at or above the sea temperature, warm moist air moving over the colder sea will fog. Classic on south-westerly winds in the Channel in spring and early summer — and it does not need a calm."),
]),
]
